---
apiVersion: batch/v1
kind: Job
metadata:
  name: egapro-restore${SUFFIX_BRANCH_NAME}
  labels:
    app: egapro-restore${SUFFIX_BRANCH_NAME}
    branch: egapro${SUFFIX_BRANCH_NAME}
spec:
  template:
    spec:
      containers:
        - name: egapro-restore${SUFFIX_BRANCH_NAME}
          image: postgres:11-alpine
          command:
            - sh
          args:
            - -c
            - psql -U postgres -f /mnt/data/$(cat /mnt/data/LATEST)
          resources:
            requests:
              cpu: ${POSTGRES_RESOURCE_CPU_REQUEST}
              memory: ${POSTGRES_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${POSTGRES_RESOURCE_CPU_LIMIT}
              memory: ${POSTGRES_RESOURCE_MEMORY_LIMIT}
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: egapro${SUFFIX_BRANCH_NAME}-pg-postgresql
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: POSTGRES_EGAPRO_PASSWORD
          volumeMounts:
            - mountPath: "/mnt/data"
              name: volume
      restartPolicy: Never
      volumes:
        - name: volume
          azureFile:
            secretName: egapro-azure-storage
            shareName: emjpm-backup-restore
            readOnly: false
      initContainers:
        - name: wait-for-postgres
          image: postgres:10-alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 20m
              memory: 32Mi
          command:
            - sh
            - -c
            - |
              retry=120; # 5s * (12 * 10) = 10min
              while ! pg_isready -h ${POSTGRES_HOST} > /dev/null 2> /dev/null && [[ $(( retry-- )) -gt 0 ]];
                do
                  echo "Waiting for Postgres to go Green ($(( retry )))" ; sleep 5s ; done ;
              echo Ready;
