image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: ${IMAGE_TAG}

deployment:
  port: ${PORT}

  resources:
    limits:
      cpu: ${API_RESOURCE_CPU_LIMIT}
      memory: ${API_RESOURCE_MEMORY_LIMIT}
    requests:
      cpu: ${API_RESOURCE_CPU_REQUEST}
      memory: ${API_RESOURCE_MEMORY_REQUEST}

  livenessProbe:
    path: /api/version
    initialDelaySeconds: 20
    periodSeconds: 10
    port: ${PORT}
  readinessProbe:
    path: /api/version
    initialDelaySeconds: 20
    periodSeconds: 10
    port: ${PORT}

  env:
    - name: API_PORT
      value: "${PORT}"
    - name: KINTO_SERVER
      value: "kinto"
    - name: KINTO_BUCKET
      value: "${PROJECT}"
    - name: KINTO_LOGIN
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: KINTO_ADMIN_LOGIN
    - name: KINTO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: KINTO_ADMIN_PASSWORD
    - name: MAIL_USE_TLS
      value: ${API_MAIL_USE_TLS}
    - name: MAIL_PORT
      value: "465"
    - name: MAIL_FROM
      value: "Index EgaPro <contact@${PROJECT}.beta.gouv.fr>"
    - name: MAIL_HOST
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: MAIL_HOST
    - name: MAIL_USERNAME
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: MAIL_USERNAME
    - name: MAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: MAIL_PASSWORD
    - name: API_SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: ${PROJECT}
          key: API_SENTRY_DSN
    - name: API_SENTRY_ENVIRONMENT
      value: "development"

service:
  port: ${PORT}
  targetPort: ${PORT}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUAverageUtilizationPercentage: 80
  targetMemoryAverageUtilizationPercentage: 80
