---
apiVersion: v1
kind: Secret
metadata:
  name: egapro-azure-storage${SUFFIX_BRANCH_NAME}
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
