---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage
  labels:
    app: ${PROJECT}
    component: secret
    namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
