---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage
  labels:
    app: egapro
    component: secret
    branch: egapro${SUFFIX_BRANCH_NAME}
    job: "${CI_JOB_ID}"
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
