---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage
  labels:
    app: ${STARTUP}
    component: secret
    namespace: ${STARTUP}-${NAMESPACE_ENVIRONMENT}
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
