-- Safe pruning migration (idempotent): drop constraint/table only if they exist.
-- This file was generated by prisma migrate diff (dev->pruned schema) and made safe
-- Create tables for representation_equilibree feature on an empty DB.
-- This migration is safe to run on an empty database (uses IF NOT EXISTS).

BEGIN;

-- Table: representation_equilibree
CREATE TABLE IF NOT EXISTS representation_equilibree (
  siren varchar NOT NULL,
  year integer NOT NULL,
  modified_at timestamptz,
  declared_at timestamptz,
  data jsonb,
  ft tsvector,
  PRIMARY KEY (siren, year)
);

CREATE INDEX IF NOT EXISTS idx_representation_equilibree_year ON representation_equilibree(year);
CREATE INDEX IF NOT EXISTS idx_siren ON representation_equilibree(siren);

-- Table: search_representation_equilibree (search helper for representation_equilibree)
CREATE TABLE IF NOT EXISTS search_representation_equilibree (
  siren varchar NOT NULL,
  year integer NOT NULL,
  declared_at timestamptz,
  ft tsvector,
  region varchar(2),
  departement varchar(3),
  section_naf char(1),
  PRIMARY KEY (siren, year),
  CONSTRAINT fk_representation_equilibree FOREIGN KEY (siren, year) REFERENCES representation_equilibree(siren, year) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_representation_equilibree_declared_at ON search_representation_equilibree(declared_at);
CREATE INDEX IF NOT EXISTS idx_representation_equilibree_departement ON search_representation_equilibree(departement);
CREATE INDEX IF NOT EXISTS idx_representation_equilibree_naf ON search_representation_equilibree(section_naf);
CREATE INDEX IF NOT EXISTS idx_representation_equilibree_region ON search_representation_equilibree(region);
CREATE INDEX IF NOT EXISTS idx_search_representation_equilibree_siren ON search_representation_equilibree(siren);
CREATE INDEX IF NOT EXISTS idx_search_representation_equilibree_year ON search_representation_equilibree(year);

-- Full-text GIN indexes (if pg_trgm or tsvector used later)
-- Note: creating a GIN index on a tsvector column requires the column to exist; if you plan to compute tsvector on the fly, use an expression index.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'idx_representation_equilibree_ft') THEN
    BEGIN
      -- create index if column exists
      IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='search_representation_equilibree' AND column_name='ft') THEN
        EXECUTE 'CREATE INDEX idx_representation_equilibree_ft ON search_representation_equilibree USING GIN(ft)';
      END IF;
    END;
  END IF;
END$$;

COMMIT;

-- End of migration: creates the minimal tables required for the representation_equilibree feature.

