packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2

patchedDependencies:
  '@react-pdf/render@4.4.1': patches/@react-pdf__render@4.4.1.patch
