---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kinto
  labels:
    app: ${PROJECT}
    component: kinto
    namespace: ${PROJECT}-${BRANCH_HASH}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kinto
  template:
    metadata:
      labels:
        app: ${PROJECT}
        component: kinto
        namespace: ${PROJECT}-${BRANCH_HASH}
    spec:
      containers:
      - name: kinto
        image: kinto/kinto-server:${KINTO_VERSION}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: ${PORT}
        resources:
          requests:
            cpu: ${KINTO_RESOURCE_CPU_REQUEST}
            memory: ${KINTO_RESOURCE_MEMORY_REQUEST}
          limits:
            cpu: ${KINTO_RESOURCE_CPU_LIMIT}
            memory: ${KINTO_RESOURCE_MEMORY_LIMIT}
        env:
          - name: KINTO_CACHE_BACKEND
            value: "kinto.core.cache.memcached"
          - name: KINTO_CACHE_HOSTS
            value: "${PROJECT}-${BRANCH_HASH}-memcached:11211 ${PROJECT}-${BRANCH_HASH}-memcached:11211"
          - name: KINTO_STORAGE_BACKEND
            value: "kinto.core.storage.postgresql"
          - name: KINTO_STORAGE_URL
            value: "postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${PROJECT}-${BRANCH_HASH}-pg-postgresql/postgres"
          - name: KINTO_PERMISSION_BACKEND
            value: "kinto.core.permission.postgresql"
          - name: KINTO_PERMISSION_URL
            value: "postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${PROJECT}-${BRANCH_HASH}-pg-postgresql/postgres"
          - name: KINTO_EXPERIMENTAL_COLLECTION_SCHEMA_VALIDATION
            value: "1"
          - name: KINTO_BATCH_MAX_REQUESTS
            value: "10000"
      initContainers:
      - name: wait-for-postgres
        image: postgres:${POSTGRES_JOB_VERSION}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi
        command:
        - sh
        - -c
        - |
          retry=120; # 5s * (12 * 10) = 10min
          while ! pg_isready -h ${PROJECT}-${BRANCH_HASH}-pg-postgresql > /dev/null 2> /dev/null && [[ $(( retry-- )) -gt 0 ]];
            do
              echo "Waiting for Postgres to go Green ($(( retry )))" ; sleep 5s ; done ;
          echo Ready;
