---
kind: Job
apiVersion: batch/v1
metadata:
  name: egapro-init-kinto${SUFFIX_BRANCH_NAME}
  labels:
    app: egapro-init-kinto
    branch: egapro${SUFFIX_BRANCH_NAME}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - image: ${EGAPRO_REGISTRY}/kinto:${IMAGE_TAG}
        name: egapro-init-kinto
        env:
          - name: KINTO_SERVER
            value: "kinto${SUFFIX_BRANCH_NAME}"
          - name: KINTO_LOGIN
            valueFrom:
              secretKeyRef:
                name: egapro-secret
                key: KINTO_ADMIN_LOGIN
          - name: KINTO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: egapro-secret
                key: KINTO_ADMIN_PASSWORD
        resources:
          requests:
            cpu: ${INIT_KINTO_RESOURCE_CPU_REQUEST}
            memory: ${INIT_KINTO_RESOURCE_MEMORY_REQUEST}
          limits:
            cpu: ${INIT_KINTO_RESOURCE_CPU_LIMIT}
            memory: ${INIT_KINTO_RESOURCE_MEMORY_LIMIT}
      restartPolicy: Never
