---
kind: Service
apiVersion: v1
metadata:
  name: kinto
  labels:
    app: egapro
    component: kinto
    namespace: egapro-${ENVIRONMENT_NAME}
    job: "${CI_JOB_ID}"
spec:
  selector:
    component: kinto
  ports:
  - port: ${PORT}
    name: kinto
