---
apiVersion: v1
kind: Service
metadata:
  name: kinto
  labels:
    app: egapro
    component: kinto
    branch: egapro${SUFFIX_BRANCH_NAME}
    job: "${CI_JOB_ID}"
spec:
  type: NodePort
  ports:
    - port: ${PORT}
  selector:
    component: kinto
