---
kind: Service
apiVersion: v1
metadata:
  name: kinto
  labels:
    app: ${STARTUP}
    component: kinto
    namespace: ${STARTUP}-${NAMESPACE_ENVIRONMENT}
spec:
  selector:
    component: kinto
  ports:
  - port: ${PORT}
    name: kinto
