CREATE TABLE "app_gip_mds_data" (
	"siren" varchar(9) NOT NULL,
	"year" integer NOT NULL,
	"imported_at" timestamp with time zone,
	"period_start" date,
	"period_end" date,
	"workforce_ema" numeric(9, 2),
	"men_count_annual_global" numeric(9, 2),
	"women_count_annual_global" numeric(9, 2),
	"men_count_hourly_global" numeric(9, 2),
	"women_count_hourly_global" numeric(9, 2),
	"men_count_annual_variable" numeric(9, 2),
	"women_count_annual_variable" numeric(9, 2),
	"global_annual_mean_gap" numeric(9, 4),
	"global_annual_mean_women" numeric(9, 2),
	"global_annual_mean_men" numeric(9, 2),
	"global_hourly_mean_gap" numeric(9, 4),
	"global_hourly_mean_women" numeric(9, 2),
	"global_hourly_mean_men" numeric(9, 2),
	"variable_annual_mean_gap" numeric(9, 4),
	"variable_annual_mean_women" numeric(9, 2),
	"variable_annual_mean_men" numeric(9, 2),
	"variable_hourly_mean_gap" numeric(9, 4),
	"variable_hourly_mean_women" numeric(9, 2),
	"variable_hourly_mean_men" numeric(9, 2),
	"global_annual_median_gap" numeric(9, 4),
	"global_annual_median_women" numeric(9, 2),
	"global_annual_median_men" numeric(9, 2),
	"global_hourly_median_gap" numeric(9, 4),
	"global_hourly_median_women" numeric(9, 2),
	"global_hourly_median_men" numeric(9, 2),
	"variable_annual_median_gap" numeric(9, 4),
	"variable_annual_median_women" numeric(9, 2),
	"variable_annual_median_men" numeric(9, 2),
	"variable_hourly_median_gap" numeric(9, 4),
	"variable_hourly_median_women" numeric(9, 2),
	"variable_hourly_median_men" numeric(9, 2),
	"variable_proportion_women" numeric(9, 4),
	"variable_proportion_men" numeric(9, 4),
	"annual_quartile_threshold1" numeric(9, 2),
	"annual_quartile_threshold2" numeric(9, 2),
	"annual_quartile_threshold3" numeric(9, 2),
	"annual_quartile1_proportion_women" numeric(9, 4),
	"annual_quartile2_proportion_women" numeric(9, 4),
	"annual_quartile3_proportion_women" numeric(9, 4),
	"annual_quartile4_proportion_women" numeric(9, 4),
	"annual_quartile1_proportion_men" numeric(9, 4),
	"annual_quartile2_proportion_men" numeric(9, 4),
	"annual_quartile3_proportion_men" numeric(9, 4),
	"annual_quartile4_proportion_men" numeric(9, 4),
	"hourly_quartile_threshold1" numeric(9, 2),
	"hourly_quartile_threshold2" numeric(9, 2),
	"hourly_quartile_threshold3" numeric(9, 2),
	"hourly_quartile1_proportion_women" numeric(9, 4),
	"hourly_quartile2_proportion_women" numeric(9, 4),
	"hourly_quartile3_proportion_women" numeric(9, 4),
	"hourly_quartile4_proportion_women" numeric(9, 4),
	"hourly_quartile1_proportion_men" numeric(9, 4),
	"hourly_quartile2_proportion_men" numeric(9, 4),
	"hourly_quartile3_proportion_men" numeric(9, 4),
	"hourly_quartile4_proportion_men" numeric(9, 4),
	"confidence_index" numeric(9, 4),
	"confidence_exotic_contracts" numeric(9, 4),
	"confidence_unit_measure" numeric(9, 4),
	"confidence_suspension_ratio" numeric(9, 4),
	"confidence_long_suspensions" numeric(9, 4),
	"confidence_no_end_suspensions" numeric(9, 4),
	"confidence_sick_leave_ratio" numeric(9, 4),
	"confidence_long_sick_leave" numeric(9, 4),
	"confidence_no_sick_leave" numeric(9, 4),
	"confidence_quota250" numeric(9, 4),
	"confidence_quota0" numeric(9, 4),
	"confidence_multi_year" numeric(9, 4),
	"confidence_fp_ratio" numeric(9, 4),
	"confidence_extreme_remuneration" numeric(9, 4),
	"confidence_extreme_rate" numeric(9, 4),
	CONSTRAINT "app_gip_mds_data_siren_year_pk" PRIMARY KEY("siren","year")
);
--> statement-breakpoint
CREATE INDEX "gip_mds_data_siren_idx" ON "app_gip_mds_data" USING btree ("siren");