DROP TABLE "app_declaration_category" CASCADE;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_a_annual_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_a_annual_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_a_hourly_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_a_hourly_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_b_annual_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_b_annual_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_b_hourly_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_b_hourly_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_c_annual_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_c_annual_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_c_hourly_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_c_hourly_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_d_annual_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_d_annual_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_d_hourly_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_d_hourly_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_e_women" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_e_men" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_threshold1" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_threshold2" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_threshold3" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_threshold4" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_women1" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_women2" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_women3" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_women4" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_men1" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_men2" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_men3" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_annual_men4" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_threshold1" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_threshold2" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_threshold3" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_threshold4" numeric;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_women1" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_women2" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_women3" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_women4" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_men1" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_men2" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_men3" integer;--> statement-breakpoint
ALTER TABLE "app_declaration" ADD COLUMN "indicator_f_hourly_men4" integer;