-- Data-only repair (#4784). Declarations saved before #4730 (proportions) and
-- #4668 (gaps) hold ratios that the numeric(9,4) cast ROUNDED, so the observatory,
-- the public API and the exports read 51,43 % where the recap and the PDF, which
-- recompute from the operands, read 51,42 %. Both surfaces now follow the single
-- rule of computeIndicatorPercentages: 2 decimals, truncated, never rounded.
--
-- The 26 ratios are recomputed from their operands, never re-truncated from the
-- stored value: a rounded 0.5143 cannot say whether it came from 0.51425 or 0.51434.
-- An explicit trunc() is required: assigning to numeric(9,4) alone rounds again,
-- and integer / integer would truncate to an integer, hence the numeric casts.
-- A ratio whose operands are NULL keeps its stored value, which leaves intact the
-- rows of the observatory demo seed (ratios only, no operand). The statements are
-- idempotent: a replay recomputes the same values from the same operands.
UPDATE "app_declaration" SET
	"annual_quartile1_proportion_women" = CASE WHEN "indicator_f_annual_women1" IS NULL OR "indicator_f_annual_men1" IS NULL THEN "annual_quartile1_proportion_women" WHEN "indicator_f_annual_women1" + "indicator_f_annual_men1" = 0 THEN NULL ELSE trunc("indicator_f_annual_women1"::numeric / ("indicator_f_annual_women1" + "indicator_f_annual_men1"), 4) END,
	"annual_quartile1_proportion_men" = CASE WHEN "indicator_f_annual_women1" IS NULL OR "indicator_f_annual_men1" IS NULL THEN "annual_quartile1_proportion_men" WHEN "indicator_f_annual_women1" + "indicator_f_annual_men1" = 0 THEN NULL ELSE trunc("indicator_f_annual_men1"::numeric / ("indicator_f_annual_women1" + "indicator_f_annual_men1"), 4) END,
	"annual_quartile2_proportion_women" = CASE WHEN "indicator_f_annual_women2" IS NULL OR "indicator_f_annual_men2" IS NULL THEN "annual_quartile2_proportion_women" WHEN "indicator_f_annual_women2" + "indicator_f_annual_men2" = 0 THEN NULL ELSE trunc("indicator_f_annual_women2"::numeric / ("indicator_f_annual_women2" + "indicator_f_annual_men2"), 4) END,
	"annual_quartile2_proportion_men" = CASE WHEN "indicator_f_annual_women2" IS NULL OR "indicator_f_annual_men2" IS NULL THEN "annual_quartile2_proportion_men" WHEN "indicator_f_annual_women2" + "indicator_f_annual_men2" = 0 THEN NULL ELSE trunc("indicator_f_annual_men2"::numeric / ("indicator_f_annual_women2" + "indicator_f_annual_men2"), 4) END,
	"annual_quartile3_proportion_women" = CASE WHEN "indicator_f_annual_women3" IS NULL OR "indicator_f_annual_men3" IS NULL THEN "annual_quartile3_proportion_women" WHEN "indicator_f_annual_women3" + "indicator_f_annual_men3" = 0 THEN NULL ELSE trunc("indicator_f_annual_women3"::numeric / ("indicator_f_annual_women3" + "indicator_f_annual_men3"), 4) END,
	"annual_quartile3_proportion_men" = CASE WHEN "indicator_f_annual_women3" IS NULL OR "indicator_f_annual_men3" IS NULL THEN "annual_quartile3_proportion_men" WHEN "indicator_f_annual_women3" + "indicator_f_annual_men3" = 0 THEN NULL ELSE trunc("indicator_f_annual_men3"::numeric / ("indicator_f_annual_women3" + "indicator_f_annual_men3"), 4) END,
	"annual_quartile4_proportion_women" = CASE WHEN "indicator_f_annual_women4" IS NULL OR "indicator_f_annual_men4" IS NULL THEN "annual_quartile4_proportion_women" WHEN "indicator_f_annual_women4" + "indicator_f_annual_men4" = 0 THEN NULL ELSE trunc("indicator_f_annual_women4"::numeric / ("indicator_f_annual_women4" + "indicator_f_annual_men4"), 4) END,
	"annual_quartile4_proportion_men" = CASE WHEN "indicator_f_annual_women4" IS NULL OR "indicator_f_annual_men4" IS NULL THEN "annual_quartile4_proportion_men" WHEN "indicator_f_annual_women4" + "indicator_f_annual_men4" = 0 THEN NULL ELSE trunc("indicator_f_annual_men4"::numeric / ("indicator_f_annual_women4" + "indicator_f_annual_men4"), 4) END,
	"hourly_quartile1_proportion_women" = CASE WHEN "indicator_f_hourly_women1" IS NULL OR "indicator_f_hourly_men1" IS NULL THEN "hourly_quartile1_proportion_women" WHEN "indicator_f_hourly_women1" + "indicator_f_hourly_men1" = 0 THEN NULL ELSE trunc("indicator_f_hourly_women1"::numeric / ("indicator_f_hourly_women1" + "indicator_f_hourly_men1"), 4) END,
	"hourly_quartile1_proportion_men" = CASE WHEN "indicator_f_hourly_women1" IS NULL OR "indicator_f_hourly_men1" IS NULL THEN "hourly_quartile1_proportion_men" WHEN "indicator_f_hourly_women1" + "indicator_f_hourly_men1" = 0 THEN NULL ELSE trunc("indicator_f_hourly_men1"::numeric / ("indicator_f_hourly_women1" + "indicator_f_hourly_men1"), 4) END,
	"hourly_quartile2_proportion_women" = CASE WHEN "indicator_f_hourly_women2" IS NULL OR "indicator_f_hourly_men2" IS NULL THEN "hourly_quartile2_proportion_women" WHEN "indicator_f_hourly_women2" + "indicator_f_hourly_men2" = 0 THEN NULL ELSE trunc("indicator_f_hourly_women2"::numeric / ("indicator_f_hourly_women2" + "indicator_f_hourly_men2"), 4) END,
	"hourly_quartile2_proportion_men" = CASE WHEN "indicator_f_hourly_women2" IS NULL OR "indicator_f_hourly_men2" IS NULL THEN "hourly_quartile2_proportion_men" WHEN "indicator_f_hourly_women2" + "indicator_f_hourly_men2" = 0 THEN NULL ELSE trunc("indicator_f_hourly_men2"::numeric / ("indicator_f_hourly_women2" + "indicator_f_hourly_men2"), 4) END,
	"hourly_quartile3_proportion_women" = CASE WHEN "indicator_f_hourly_women3" IS NULL OR "indicator_f_hourly_men3" IS NULL THEN "hourly_quartile3_proportion_women" WHEN "indicator_f_hourly_women3" + "indicator_f_hourly_men3" = 0 THEN NULL ELSE trunc("indicator_f_hourly_women3"::numeric / ("indicator_f_hourly_women3" + "indicator_f_hourly_men3"), 4) END,
	"hourly_quartile3_proportion_men" = CASE WHEN "indicator_f_hourly_women3" IS NULL OR "indicator_f_hourly_men3" IS NULL THEN "hourly_quartile3_proportion_men" WHEN "indicator_f_hourly_women3" + "indicator_f_hourly_men3" = 0 THEN NULL ELSE trunc("indicator_f_hourly_men3"::numeric / ("indicator_f_hourly_women3" + "indicator_f_hourly_men3"), 4) END,
	"hourly_quartile4_proportion_women" = CASE WHEN "indicator_f_hourly_women4" IS NULL OR "indicator_f_hourly_men4" IS NULL THEN "hourly_quartile4_proportion_women" WHEN "indicator_f_hourly_women4" + "indicator_f_hourly_men4" = 0 THEN NULL ELSE trunc("indicator_f_hourly_women4"::numeric / ("indicator_f_hourly_women4" + "indicator_f_hourly_men4"), 4) END,
	"hourly_quartile4_proportion_men" = CASE WHEN "indicator_f_hourly_women4" IS NULL OR "indicator_f_hourly_men4" IS NULL THEN "hourly_quartile4_proportion_men" WHEN "indicator_f_hourly_women4" + "indicator_f_hourly_men4" = 0 THEN NULL ELSE trunc("indicator_f_hourly_men4"::numeric / ("indicator_f_hourly_women4" + "indicator_f_hourly_men4"), 4) END,
	"variable_proportion_women" = CASE WHEN "indicator_e_women" IS NULL OR "total_women" IS NULL THEN "variable_proportion_women" WHEN "total_women" = 0 THEN NULL ELSE trunc("indicator_e_women"::numeric / "total_women"::numeric, 4) END,
	"variable_proportion_men" = CASE WHEN "indicator_e_men" IS NULL OR "total_men" IS NULL THEN "variable_proportion_men" WHEN "total_men" = 0 THEN NULL ELSE trunc("indicator_e_men"::numeric / "total_men"::numeric, 4) END;--> statement-breakpoint
-- Gaps keep the GIP priority of resolveGapRatio: while both operands still equal
-- the GIP ones the published gap stays authoritative, otherwise (men - women) / men.
UPDATE "app_declaration" AS d SET
	"global_annual_mean_gap" = CASE WHEN d."indicator_a_annual_women" IS NULL OR d."indicator_a_annual_men" IS NULL THEN d."global_annual_mean_gap" WHEN g."global_annual_mean_gap" IS NOT NULL AND d."indicator_a_annual_women" = g."global_annual_mean_women" AND d."indicator_a_annual_men" = g."global_annual_mean_men" THEN trunc(g."global_annual_mean_gap", 4) WHEN d."indicator_a_annual_men" = 0 THEN NULL ELSE trunc((d."indicator_a_annual_men" - d."indicator_a_annual_women") / d."indicator_a_annual_men", 4) END,
	"global_hourly_mean_gap" = CASE WHEN d."indicator_a_hourly_women" IS NULL OR d."indicator_a_hourly_men" IS NULL THEN d."global_hourly_mean_gap" WHEN g."global_hourly_mean_gap" IS NOT NULL AND d."indicator_a_hourly_women" = g."global_hourly_mean_women" AND d."indicator_a_hourly_men" = g."global_hourly_mean_men" THEN trunc(g."global_hourly_mean_gap", 4) WHEN d."indicator_a_hourly_men" = 0 THEN NULL ELSE trunc((d."indicator_a_hourly_men" - d."indicator_a_hourly_women") / d."indicator_a_hourly_men", 4) END,
	"variable_annual_mean_gap" = CASE WHEN d."indicator_b_annual_women" IS NULL OR d."indicator_b_annual_men" IS NULL THEN d."variable_annual_mean_gap" WHEN g."variable_annual_mean_gap" IS NOT NULL AND d."indicator_b_annual_women" = g."variable_annual_mean_women" AND d."indicator_b_annual_men" = g."variable_annual_mean_men" THEN trunc(g."variable_annual_mean_gap", 4) WHEN d."indicator_b_annual_men" = 0 THEN NULL ELSE trunc((d."indicator_b_annual_men" - d."indicator_b_annual_women") / d."indicator_b_annual_men", 4) END,
	"variable_hourly_mean_gap" = CASE WHEN d."indicator_b_hourly_women" IS NULL OR d."indicator_b_hourly_men" IS NULL THEN d."variable_hourly_mean_gap" WHEN g."variable_hourly_mean_gap" IS NOT NULL AND d."indicator_b_hourly_women" = g."variable_hourly_mean_women" AND d."indicator_b_hourly_men" = g."variable_hourly_mean_men" THEN trunc(g."variable_hourly_mean_gap", 4) WHEN d."indicator_b_hourly_men" = 0 THEN NULL ELSE trunc((d."indicator_b_hourly_men" - d."indicator_b_hourly_women") / d."indicator_b_hourly_men", 4) END,
	"global_annual_median_gap" = CASE WHEN d."indicator_c_annual_women" IS NULL OR d."indicator_c_annual_men" IS NULL THEN d."global_annual_median_gap" WHEN g."global_annual_median_gap" IS NOT NULL AND d."indicator_c_annual_women" = g."global_annual_median_women" AND d."indicator_c_annual_men" = g."global_annual_median_men" THEN trunc(g."global_annual_median_gap", 4) WHEN d."indicator_c_annual_men" = 0 THEN NULL ELSE trunc((d."indicator_c_annual_men" - d."indicator_c_annual_women") / d."indicator_c_annual_men", 4) END,
	"global_hourly_median_gap" = CASE WHEN d."indicator_c_hourly_women" IS NULL OR d."indicator_c_hourly_men" IS NULL THEN d."global_hourly_median_gap" WHEN g."global_hourly_median_gap" IS NOT NULL AND d."indicator_c_hourly_women" = g."global_hourly_median_women" AND d."indicator_c_hourly_men" = g."global_hourly_median_men" THEN trunc(g."global_hourly_median_gap", 4) WHEN d."indicator_c_hourly_men" = 0 THEN NULL ELSE trunc((d."indicator_c_hourly_men" - d."indicator_c_hourly_women") / d."indicator_c_hourly_men", 4) END,
	"variable_annual_median_gap" = CASE WHEN d."indicator_d_annual_women" IS NULL OR d."indicator_d_annual_men" IS NULL THEN d."variable_annual_median_gap" WHEN g."variable_annual_median_gap" IS NOT NULL AND d."indicator_d_annual_women" = g."variable_annual_median_women" AND d."indicator_d_annual_men" = g."variable_annual_median_men" THEN trunc(g."variable_annual_median_gap", 4) WHEN d."indicator_d_annual_men" = 0 THEN NULL ELSE trunc((d."indicator_d_annual_men" - d."indicator_d_annual_women") / d."indicator_d_annual_men", 4) END,
	"variable_hourly_median_gap" = CASE WHEN d."indicator_d_hourly_women" IS NULL OR d."indicator_d_hourly_men" IS NULL THEN d."variable_hourly_median_gap" WHEN g."variable_hourly_median_gap" IS NOT NULL AND d."indicator_d_hourly_women" = g."variable_hourly_median_women" AND d."indicator_d_hourly_men" = g."variable_hourly_median_men" THEN trunc(g."variable_hourly_median_gap", 4) WHEN d."indicator_d_hourly_men" = 0 THEN NULL ELSE trunc((d."indicator_d_hourly_men" - d."indicator_d_hourly_women") / d."indicator_d_hourly_men", 4) END
FROM "app_declaration" AS src
LEFT JOIN "app_gip_mds_data" AS g ON g."siren" = src."siren" AND g."year" = src."year"
WHERE d."id" = src."id";
