---
.deploy-egapro-app-k8s-dev:
  image:
    name: $CI_REGISTRY/socialgouv/docker/kubectl:0.7.1
    entrypoint: [""]
  before_script:
  - SUFFIX_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export HASH_BRANCH=$SUFFIX_BRANCH_NAME
  - export PREFIX_BRANCH_INGRESS=$SUFFIX_BRANCH_NAME-
  - export SUFFIX_BRANCH_NAME=-$SUFFIX_BRANCH_NAME
  - export K8S_NAMESPACE=egapro${SUFFIX_BRANCH_NAME}
  - export ENVIRONMENT_NAME=dev
  - envsubst < .k8s/app/deployment.yml > .k8s/app/deployment-egapro.yml
  - envsubst < .k8s/app/service.yml > .k8s/app/service-egapro.yml
  - envsubst < .k8s/app/ingress.yml > .k8s/app/ingress-egapro.yml
  - envsubst < .k8s/certificate/certificate-staging.yml > .k8s/certificate/certificate-egapro.yml
  script:
  - kubectl apply -f .k8s/app/deployment-egapro.yml -n ${K8S_NAMESPACE}
  - kubectl apply -f .k8s/app/service-egapro.yml -n ${K8S_NAMESPACE}
  - kubectl apply -f .k8s/app/ingress-egapro.yml -n ${K8S_NAMESPACE}
  - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}
  allow_failure: false

.deploy-egapro-app-k8s-master:
  image:
    name: $CI_REGISTRY/socialgouv/docker/kubectl:0.7.1
    entrypoint: [""]
  before_script:
    - export HASH_BRANCH=master
    - export PREFIX_BRANCH_INGRESS=master.
    - export SUFFIX_BRANCH_NAME=-master
    - export K8S_NAMESPACE=egapro${SUFFIX_BRANCH_NAME}
    - export ENVIRONMENT_NAME=prod
    - envsubst < .k8s/app/deployment.yml > .k8s/app/deployment-egapro.yml
    - envsubst < .k8s/app/service.yml > .k8s/app/service-egapro.yml
    - envsubst < .k8s/app/ingress.yml > .k8s/app/ingress-egapro.yml
    - envsubst < .k8s/certificate/certificate-staging.yml > .k8s/certificate/certificate-egapro.yml
  script:
    - kubectl apply -f .k8s/app/deployment-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/service-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/ingress-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}
  allow_failure: false

.deploy-egapro-app-k8s-preprod:
  image:
    name: $CI_REGISTRY/socialgouv/docker/kubectl:0.7.1
    entrypoint: [""]
  before_script:
    - export HASH_BRANCH=preprod
    - export PREFIX_BRANCH_INGRESS=preprod.
    - export SUFFIX_BRANCH_NAME=-preprod
    - export K8S_NAMESPACE=egapro${SUFFIX_BRANCH_NAME}
    - export ENVIRONMENT_NAME=preprod
    - envsubst < .k8s/app/deployment.yml > .k8s/app/deployment-egapro.yml
    - envsubst < .k8s/app/service.yml > .k8s/app/service-egapro.yml
    - envsubst < .k8s/app/ingress.yml > .k8s/app/ingress-egapro.yml
    - envsubst < .k8s/certificate/certificate-prod.yml > .k8s/certificate/certificate-egapro.yml
  script:
    - kubectl apply -f .k8s/app/deployment-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/service-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/ingress-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}
  allow_failure: false

...
