---
kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    app: egapro
    component: app
    branch: egapro${SUFFIX_BRANCH_NAME}
    job: "${CI_JOB_ID}"
spec:
  selector:
    component: app
  ports:
    - port: ${PORT}
      name: app
