---
kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    app: ${STARTUP}
    component: app
    namespace: ${STARTUP}-${ENVIRONMENT_NAME}
spec:
  selector:
    component: app
  ports:
    - port: ${PORT}
      name: app
