#!/usr/bin/env bash
if [ "${BASH_VERSINFO:-0}" -lt 4 ]; then
  for B in /opt/homebrew/bin/bash /usr/local/bin/bash; do
    [ -x "$B" ] && exec "$B" "$0" "$@"
  done
  echo "Bash 4+ required. Install via 'brew install bash'." >&2
  exit 1
fi
# publish_release_summary.sh <tag> <summary-file>
#
# Publishes (or updates) the AI-authored business changelog section in the
# body of the GitHub release for <tag>.
#
# The section is delimited by <!-- ai-changelog --> / <!-- /ai-changelog -->
# markers. Re-running the script against the same release (workflow_dispatch
# backfill, or a second run after a fix) replaces the existing section
# in-place instead of duplicating it.
#
# <summary-file> must contain the French, business-facing bullet points
# generated by the AI step. If it is empty, the script is a no-op (nothing to
# publish, release body left untouched).
#
# Usage:
#   publish_release_summary.sh <tag> <summary-file>
#
# Env:
#   GITHUB_REPOSITORY  — "owner/repo" (default: SocialGouv/egapro)
#
# Requires: gh (authenticated).

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 <tag> <summary-file>" >&2
    exit 2
fi

TAG="$1"
SUMMARY_FILE="$2"
REPO="${GITHUB_REPOSITORY:-SocialGouv/egapro}"

if [ ! -f "$SUMMARY_FILE" ]; then
    echo "[publish_release_summary] ERROR: summary file '${SUMMARY_FILE}' not found" >&2
    exit 2
fi

if [ ! -s "$SUMMARY_FILE" ]; then
    echo "[publish_release_summary] summary file is empty, nothing to publish" >&2
    exit 0
fi

START_MARKER="<!-- ai-changelog -->"
END_MARKER="<!-- /ai-changelog -->"

SECTION_FILE=$(mktemp)
NEW_BODY_FILE=$(mktemp)
trap 'rm -f "$SECTION_FILE" "$NEW_BODY_FILE"' EXIT

{
    echo "$START_MARKER"
    echo ""
    echo "## 📋 Résumé des changements"
    echo ""
    cat "$SUMMARY_FILE"
    echo ""
    echo "$END_MARKER"
} >"$SECTION_FILE"

CURRENT_BODY=$(gh release view "$TAG" --repo "$REPO" --json body --jq '.body')

if grep -qF "$START_MARKER" <<<"$CURRENT_BODY"; then
    echo "[publish_release_summary] existing ai-changelog section found on ${TAG}, replacing" >&2
    awk -v start="$START_MARKER" -v end="$END_MARKER" '
        $0 == start { skip=1; next }
        skip && $0 == end { skip=0; next }
        !skip { print }
    ' <<<"$CURRENT_BODY" >"$NEW_BODY_FILE"
else
    echo "[publish_release_summary] no existing ai-changelog section on ${TAG}, appending" >&2
    printf '%s\n' "$CURRENT_BODY" >"$NEW_BODY_FILE"
fi

echo "" >>"$NEW_BODY_FILE"
cat "$SECTION_FILE" >>"$NEW_BODY_FILE"

gh release edit "$TAG" --repo "$REPO" --notes-file "$NEW_BODY_FILE"

echo "[publish_release_summary] release ${TAG} updated" >&2
