apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: admin
  namespace: egapro
spec:
  encryptedData:
    ADMIN_EMAILS: AgAPO/KHlIJDVCnAYm7q2u2g6c/U/bTblJtWxEc3u+D85388le3uBUOGwv4Fbn32RBXXa/FX+VVvAAQ+k0i8+TuuEFVT74/A+UnqdL+NrjRKv/NjpYqtfD75reeFnbgGZ7Z7m9i0Kb888TCX2H72LGDBC6vgJe5650FM2Fs0wSTc0Lnl7/q4wO0jJn5YOjAxMvqGm/V6fk/rtdFgTabwHVFYQHDdxorRfMcwJH0+V7FmGOCeH2ye2AUyAUUoDgdPEqwmYs3QyOQVTDKSG7KbvioY3/Jh1SwxLJxmvMm2BpBdl9aYtjDOM1vKgVcfD6kAenrB4gKFUzf0L91wfmgnXwhb19r/sT6AL4Bsf8CLow2wZZ5gecVF3MRKgaBJJyDY6pRshuVT2QUSYrOkTV0kC0U08zJv0shsUinyfBWv4XYgmUHslqtLtJac9cvQnbkQU8uT6zTRNJjdswxd44G586bVmQguop37RiPzl4tNeuN1Z/YpvwJ5V0JSRuZ94wmP254njB72GW7azKULrbSEi9nL3aMhKJnYLLJg10XleSkT45kK03+kzNDZD51ZBxLCD/GNWkqsiLqaHpKDtHWrydrlTxEJk6LSnGlhwDiVNjhPUEo9/HKiN2CBqlj2K2sQ24294M7CB5SFXv2iJSDPEVxjTphYMQblvSqj8keY/MTGTIDjzb4NpXPsdWpX1spP4CaPgmIQm/TOQu5oJ1b5z/Zp9Z3yBtj/obXNDkQp2TuyHxlN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: admin
    type: Opaque
