apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: api
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_WEEZ_API_URL: AgBUEF6/k2c5fM9Q9NdrhwkJPbG0Locgxj8yueaZGeZSseVOlCQxxAMRJ/eQzAzViGNnddsMpYjuFKvzJIGJcixFpSzVKu3wds3MoxKSi8Z13VDvwusOMuv1eAZVNJPt2Oty3ldxEGwXBf2rKI5UiAh37UUt+yYcl/ZLgvb9IjMsPpfIL9ngwxKRF5HmTP1hqV3SENkjomH1vGEMuzS+hh99zqv6pw4cSEqToWXW3ZRlegXNCzRB9q/nAfeFZ/a4wNuiQm34TaWj3YWGvJ+x8YJ3gvOa4ky4hKoXg4oeoGzutsF+Qj0Soo1Deab6j6CabanYIU0jvZjvF6oJ0iF01cPbbHdBTq8ogrCWZV5YhZeiOidtqGLlEVD2u8fg+eq87rHXiDewBeZO4hovlvcZ3nRm3Ufhf3xscUNtwdPk1wM62lDQWE1J7I34/cAWwb+Xr3pqvBS7nTrpdwG3hssTPWlFfhrWG/cK45qETB1OHP/sehThsccCArA5419ZML+OV+lX/5u32ktg+JXA/iBbQnIBsffocxKz9Rn6Oaaw1gGMJ+c5+jG1h4kmGsRzXIEMLgjrToG8u0OeLUdwI9IEgorQ428Rle3HjR02NCln2i4PtpFVCdz87/jMP+yLG1I6qMbq7IB53/kG5rc4xzy3nueNdum8qlNpLePTaTQt7qjfLfva1Ok6hmZm9mf9Paiz3KddvMM70UoERvCII9Pk5OrADWeIE/7Mu0b07Rj6/xubKCXIdZeCwpxH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: api
    type: Opaque