apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: audit-cleanup
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_AUDIT_CLEANUP_TOKEN: AgBY3j0FsFuMvvcxQJlmQq3feb46uavbPkxHJ5cbBg2pMZMvHpiZlDrRqeatm8pGw19hp0c7z9cG1AOcYP57aPYoKOU4huUD64nuLRmoG4T7OKi79L39D3kCmgcA18rMBoFwoUQ1nJfQMwToSjhWO3E+g6sYj6+JysqAJcH2J+dWx/vhFcMe+3ifqW4GSxzQUlOCuKizPZeaxQm7vzCKUWBcbgpwDR3dI2U+7732kVCdTgQTtM7Rq+ERui9IQz9F92YWxUonEp0ZHM2yFMPr5LY+dnHAzlKkiN1uMkiB7czcYzbB/KAxsdXp6Z2NS14Hqa6lFh1YCtjWirPGEFnNHy+uixgK5hTG92KQcQVWGC3RSDvUmZHQYqXRmQqCMjCcLQD7bvbEOpGbxtEckozGkP5mjP3Sqk2vkFQYdC7tIA3gC7FZ6p/dAStp8A8se5yWlwdlMv0HRwsQHnw/v8LIaRvi2E1+bZdRuexAnVtEqV4fnDx5Wxa36TP9IYArt501BMBU774jnxm72keTDpn1+yga/maSRAG/rHAJ6fKcPzEBrMThOnvRTEUkhqV1G3w7JqUS5CbgeLRYigVEAVHwcZcQ89zPgNBTozR3xom/JhPOPWJ2WRGhvstDMvRd8EGI0yOQpohWkAqb1OE9Y27YBYSsS8fRseMF2vGTb0p/S2wWSTdJ9FLXpD5upQSkXv3DQ/c8hy1orFroxGKG8A3hfTve3xnty78RyH3uq1BQ4rlrCdVAlnG3/YQnhp7N4OojaW1ESt4FlWXq/wPAe6LmMdsR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: audit-cleanup
    type: Opaque
