apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: basic-auth
  namespace: egapro
spec:
  encryptedData:
    auth: AgAUMYRA0D5nIEPQPQ2zmDLPtv9GjTtwv2sPlC20jO4n2/dZpaN4t9s3S7BNEz393D99xjemsyVzvIcz86BweK7Qa1xUCJqIyP/mFG33z1O7PigjlRXu4lOK/FpOXElCoaCI+v2tN8PZ5318fxdZpPQrucACR8uNseqnyDW0cJpOra9PWv8cHTEYWaJOsf2vmKfYm7Fkj5I4kT/g01PRs5Fm2CWBWXMupDAG8xlWhtXQEyQSBoTmdENmCN5KmtXkv8rsetW8c5/etO9Wv2pT7Mrq6B1fp1du1PjSN7QLc2JmYn6cqa2+XF7Nd3nu9/dB21aGlOMLRDW4jyTvRZpxFvJO8sRksDZfeTKR/hZt8iwsfC4P3g4U2N1OMugCgo34Sm+dLzSJkMtfdGWUJ0SsoRRucAA5RKgckNSWGK7zMd/oF5MEr3SZMAqCYU14pGEHOtHgFboui5KgHX2rFokViuoHGpNA6jAhM41I9k3XBE4TShJ0rVfY00pD/BOWMJmUcNPVPaLDvXEBGZux7/McmGSV5V9GrCSvftYgg0grJ8KlUv1ykFRktfPiB2K6nQO3ZjcNM1h2Bc3qvo5dDLTccWWCZfLIaaEO0uMtG66FIABHWiXSMWOUbTynufjZv1eTFUcNidOZkQio+V+Bhp8W3/ADCcln8m1cRU1f/fCs65Y5+e0zkdrpuhj1SQW8KjOnfJ7yG6Oy08sCehJJ1mcjxqe0AcLv/9h461d9ndsC0XVHTOVbWkOHCXjhae9R9ofDGbukzkYw8gejVlZ+C3QLUiwAHA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: basic-auth
    type: Opaque
