apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  namespace: egapro
spec:
  encryptedData:
    auth: AgDL7I/aRPKrWaEqrkiXt2saSKhY4GWFhPOBmB2NqIyC+/02go0qzXmdyPCuwRit0Mp+3wDQ1pIdqtuL2CPwh9+sPZt8/LXoHw1QNHbE0PT+BHDOhc8ZoI8EpgYiYOb+b5HB0MrKgyb0RjzS8sU+Rudkbjeh6HWyNCpmYs8+uk2Z+6ooRnPFPMnzBuvGZmvRft0h5onpwYE4TATzrOxMFv6VolRlveTp6UM4DJ461yUD8XCkotCWG7I61Sp4CI7kEx7eHEHnM8AxG+PTf5jx7OzYjmDZUB/JmMHRxnb0HVmAmS7lrOdoxFqjookxi5xfpXTJP2SnM9n95P2o0zzNWX6oA4AHM1laLopHp6CDXP7JpBeToRnGMbc3F9ml1OMJ5GZ8S4myrFQoWm5W/GkGZPS/Jy4haj3qiSZ8q1AzP/zJUTN5xLkRSVewK2YXngSZr/VsHG6cdeYUH464kgoJNmkqSZOQQ3Ahe0T+MnJPP2Yh418FC1OEodhnDyLQItiX2fYPJKC9wc53KU8Mguwwok5Hrxj5Dg28SY5JiSaPqY/yfF818DP2BeiYNHtpHh2OxUxvjOnOugzY/r1Tb813ZYmIW1G6pjLwCgsgHQ/tCAVyIjDZsJQxjKg82gmghOsM60GJZMS76DIb2X/lGB3gzSbv+GFbFOq0raDcOtSSXv5KQ+AdYYkKuvaOu7yqnuVSwz4jcLNie+uVCwDN0a4RB7NbTMIEL3u1+V07tDRyCEEE6i7/Fik0gudcuRmfxMpQqP612vuUqQFshEL1VETj/1BuZ+15ZW317Fy9DCG/7s7gnBYZeHNIesQBY0+QeAJxax9We7Jl+3OTLyGN331m6fn9yS/9+InMmQCgmbotd8IVwGqAAUPhQjl9Hz9s3iA/NqLGIBD3JE3O/7pm20o4z+wlf/WIj5iRmvDh
  template:
    metadata:
      name: basic-auth
      namespace: egapro
    type: Opaque

