apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: egapro-secret
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_SECRET: AgASWV6jlnscCZesKzL+HRhwjz0mCIVCVvv8qQjHd4uS32BJ3riJxKZuhIBYYoQ5aCDQJh55pIMX6fykpUawEHBygw4ugvEltiBkoNb+x26PGtdCPoPPG/imfPAO2yrxX6UbmOyl5hvkcZpyMHYfxYTItgxxhcmY7VN20+u0nLS04R7S6CUaQ897Le3VbpfsXwChAirmOrT1EPWIgSIP5++neabf7vvsyI7cYtxESb8E0A0iKMu7zeWGDk1ZyBfWttmkyYIDsd4G+oXWY8xd0YUpMtd0xnGeyJxMKGaP+RUYdZPrV6NmI82PwPaYsH+ZTaf3uZYlVoiZllRFFTiN0tjv7djQQDIdkxN8zvkLLtkuG8vBcitDX8SCHt7UAUR3j45dlN4Ioy7KdP3GSDs69kBUh+WzjjGA8IsosvG1inLz14XhxXLfQ1StmDtTk3wk+y2JhKLwP7q2pS+ULY7UVECEb65ZPC6Zxq4SB0ffAbATwHp8Kros0vNC/01dLvmPD4dM27w9/pGJI/jFFkHJA0ZNqxwxCRm7/hRxht48Zi/eaP/RqqF6n0If/YfH9/bvLckIWEIxuu6aUYD9gNqQIcseKE2ohJPUMu4YP6rifXxUp1jXZhM+aKkQ9oObmqOJugOy6upFwxfyuUZxcsGl1L66tpwF0hzioSAu5quL/PXeubnQhnu2RQnpRPjCI7JmtXKipUXOuPwNiiPO/J0xmAZMf9kQyGMxldMfdgQ7Iwh2KWRmZUGjwzKWmtpCPoCUSJnj7a45DzQw5MWohT7ZAjkS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: egapro-secret
    type: Opaque
