apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: export-api
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgCo+94GD1ws49ufkZnHgWNGUvkqklKG5PMvxtJmntnqmJznv/gbYkKqc2San+gg9/lDV9umTwlyQ6VS1a/KpOoFQ1m9vc/biVr/HbsDXewkqLjhMtul13IERMgN0jhB6EUXGF9X5SFlKH56EoEdyNQCzLtP6p225AfKNZ4/c6XD0bvcjh9hUOa0AK5gd8VPZ6Zu4l9y/6IqnX9gS9ehkGPJJ8NXXExO7Y6pmUET3mGRWzM6jaqhk5Lr/RAQTTAjawpBT9vYxKk7dARnwJ59iOD/4I/1GsA6JTROLyEmDVEW0IlF7qDfgQu9ICkaNVBXeh0nsIhWiY2/OMGa3RZElhQCfTHfthB7TnExjytQncoreyP8QEcwVhDTlJZ8EvGtYGnlGz4QohxcPr95fUG5tGHhfXn9M/pxH7HYu+1UkjoUUVUK4qHTtwjlqkE9YxsRoUAtfRIn+SFOUsUU3EYIvj6sn22rm8YQL/5Q4E/OgoFSfYQ8eoO9OJ4Y9/f3ZnIjedmAgYkh36LxIv3+0tJ0lH6NKYyetxVw8Ho2Ix9UkIqHhmxXbgmqAupPfMl8x4lkzJEWP/wijcY8AWlMr4q90uUV3jkB9/cSfFV2s5Nv1c5NlPZw8l0qT4ApFgSBCtEou+IhX/lEH0KXOOMVt0g+nrJ9rqoGrweXmEjNIfV4qkePT0sqsLCHZyb6tEdvNDgnxEgf/Vffe2HZtTpN+WxfjnwQIeBUflMDg5fvTBl/L2MrKRA7F6auZKWcaiHL4As1Aus=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: export-api
    type: Opaque
