apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: export-api
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgBwKgRKSZ15qAv2t5SALQSMzeJXeArGYnYmNUHo1fsBNnK9Bh1kRGYouhBuxNMklRQ/QiH0xbfTlq5jItyLCmcfFj5aEkxtwAuVO1LbF2p8MQXmRnLut1Jr59XAkykj4TwXZ0qCY7+G7oHbd5h6OEWKAitapX3UegB8rMVRDu8QUz3CNhsI2wTYkCNrljNjDEpeBm1erMBtrZD1S9WQS3QskLhYKJdQ6IIUtm9dCtBaKMdJN0g0x/8usRKdGPUbCzlhwqvh0BLN9KxvXJfXIvta5OeIHpgVZ82viEaXz3unA7aFqHCpW2CD6c+HP2TkZZ/M8I3LxPEbYnrRy1gzPFkDmPmdPfeKr6nl1pvUm1dTXYSHgmOE94kEWYzYxEp+sR0nObHoz++T/UZxlrkayi7SOX4/eIHH8029H6OWXtG/Tf+wbro8uzQWFaVIukgJ5aywGYPLe89w6BUHGndZ8rLe70Y3P3KFsZ/VQ3wmLu5U4nBPoriKT/9q91BN7kr9DjFG48WMcQcEYLmDZTnacjZNss5JRUEbqzuLg43N25aCb1X9yQmmbI+QoJkFNq/hndVNiamspDmzWqvSAIeOcoECxiOOQ6560O2SYQXLQBd8AccUHEtoScuvB2XlTxDBHncfeQbrJfCErocEKNlxNNo2a7Up/+QJR39aYWPvKv+SJbAlF41J/j9GtDQX3rq7OFJWz+07pqKYI5uFmUUzlStuN1Yilu9SEROo7JUHpOEGF4c8at+MT6mMDBYsgMh8+R4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: export-api
    type: Opaque
