apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: gip-mds-import
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_GIP_MDS_API_TOKEN: AgBXrJewS7A9LxDBvSLVvxiN4twUWgc27817MQU2FAAAwr3ulJxlyI3iJKUwnJgIGd2mXnlCc0+szjj5eC37hMzJN/NoOAD/BnLVEIcgXJ4mwM90MSdtzgG4hpZJKCxSatqOaPOO36u9tRPBqD3GWUdu38EEBwbpoJp0tOO/vF4VCvv9whjS7BQq/Iywe0PDK2HC63fnmUq9rn+Q+gN/5VfV3NBqSYjs0Y8CW326/xwcapNluy4bnNkciKnyRi6rHzf0TkThceh65pdahR+1U2TueucwgRuuVnauw9EOAv/iWc3xMi0W1dewrUicW9E7bIWI7pFCcJlInecl4doGesWQ8iwgnI0SF4LjoGUdNIBqhjF9YYSmsyh2Lh7N7nZd5uRyjyv0LAbfzr/5FrsFjjgxT1jlHVie7bMIEjW8uNU2HJL+kxCbpCuKY0rNoQQBDgIYssPRyrpXjUj+lZhXRiyXnC2YbnAYFaB+4ZJ3QpfkLBmVL9d1Z1zixktnCDS28y8naK/J2iGmULhICwF1SaCJvV0lGq/O+AJRrscrOtOrmCi4R7csXeqdVvDYiDCBQ4jgYOb+M/Xr93Sc/rbBoj/1zibyVC6PnfSxAaHeay1dJaeslHQvLPPW3mdr6m668+ZMSD8drc6yg7J5Q4AdtN7RJnRixcOnWg+zbMDRby2uZw/rRjjihNjOpJvYH1SMHDzHaHBnCTYDz0r/KUwTnx2sGI0rX7j7h2ww83apJgPTgjWTAmorltOiPebrbQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: gip-mds-import
    type: Opaque
