apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: next-auth
  namespace: egapro
spec:
  encryptedData:
    AUTH_SECRET: AgCTq7EPyv5ift1L1mv41SDR0V9k/sCQy9+1TMSJPFojYMSARstb7dzvU+W4oAdiGtdSr3WnGQofyo+NL0KBlWa5Kd0bWVe7mPLdtGHWIqLlbzqtalbaBTAe9um8CsavFEJvuV6eya+FRkKy2sfM7cWIeNMlurrLEDQZoAFOspRq1V1uhh8LBUi/MRmB7d7Q+l1w2rzdT9uPPqLOs9knrVV0Ez83vUf6JyZIxgLuNzN4OBRroISgCD6cS9KewVdCT79nn3O0jlYwC++Dut7gTkCNc/TK2SCiro+vfC+T8RI4PtxFlip/l8bj6WNXw6XkcUHYPhoz67E+2CsAk+MonaG2LIqYRi8Jc7hcKNhsGd3qLolzY6ze5eMlKOTQrqxvBSHpaALJqdPQWQbxluk1VbwSon3sDVhgKt39jzZnS9wynsCTYQ5CVgHBLiQJmOuu/k5rllPfA6Jz7kU+EmaNmMMSjaJmbnMltzj5WXy9nh79cK5CtN76xQQamApAyRtIiaSxicn99n3la3txsGnbcV/MV9LWF8sgAdCU84e1HWlcl9gYgGqpKVTizeOoTdvtXYthC6Ig50f/Dn+PQxPmxh5bn6aV8p+m8M5EIhDZE69OJyRqSJxfH8u14j+hqCA1H5SyJBKRhuBQ1cBgVWeXbnrBkBnMb6eIw5L4ZrsK39Yj+/pIhIvMYKBJYbcea1HK4Vu/7G9KziDZ5Jc9mGHZ8ykuqQ3DfGh08KKTsoFPaOLPow/DBQ7YaXO2Ifv2YA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: next-auth
    type: Opaque