apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: proconnect
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_PROCONNECT_CLIENT_ID: AgBNld+DWPkvfgCppWx1hsuYTulIsc5nrrdFG3bGQ3iE26+Cl7aPXohEf50uQO7l1YSkKrPNgYiXnYDgh1lAxPTEBL1X2pHg9kdL4wlrpn37XAEMdpSNJfoIqwrOXczqNQXeZberQ9YtqPBUTQuoolPF9dbW5Dkcd/bjNd5b2m8STtD8nt3jfadZApMZlfjH5uBTL6c2TPi0nUYlpnNPYJ8ZazNyss4+/HaQMpthyTAgB9xZDoALpQNiLnoT7R2VEnnja84cQeO6TfMmgvnf623qsKa4MDIaJG5e8sNSQRrXDOJ0EJXmCaeUE4189rFFTDRo4qeFwgjDdXs6cS5qP0fT2nhYYQeccI0yTb/RF+Kk+5vHtqN+GjlZEWM8mUklP6BX9O5xdRUD5AdnV+g6Ab9O+At4tkqJPNbsLjJZC8/dneoVh71WycKyIMSLMpFVWIC2ajOuwmGsAMVgrAVHkZJHYFO4FPRyHLgCtJV4IBZXV3dlYFbSqVL2YcrcoIZkON0epLS1zgHoIuRkuJt6htPySjMwpM+5k7E+WqGEOSRZSr0NcugOmRNaI+WUhSdiSLO4gCQRrqyMPNVdrMp3JYW1ig4z5UlXPULg4f7ihYyrPHPzX1TwvuCsIMbcsMK4dzN9qFM2YN96Wufwle0bp8RTcrYNhtJMKaOnvazfmhQZdzbAwb+SztqnuqwktGMkoQm4blF0SH764m+OCc1YX3TNRf/fcTb3Xadq4TQL+9ygzsKk4AA=
    EGAPRO_PROCONNECT_CLIENT_SECRET: AgAzTZ69MybTa4+ety1NITuwT8oE0THuFr0vud5gkCaxHq1au3LRJKXEPckG6PHQxYvuZb0jwFKBDI9Yjmd0wQL15exX1oSU+Xm0ia7obc/QGbfSLt1j9tOeZ1bMlQNIY/pImwnbur+GtFISFvqjd9xWIrdTVzyVQWRXnbPilOm/+Mlbmj+gDJdsvmDblIO8H5QYcf+OKsMAFlDZhm7/juKcCJ/GcXCszJRdhNpvNuxYop03O4ust7r1+Nyul6eqJWL9C5/t4Nm544kez4ffZr6RGPLI6I+UqinLW+NmDue58pvWTLiXEGTNs60ehoW6B0L4Uf0IBUpLkp1eHloC6IIB784P/OydTEmIykQdhPRNgEG5VYQ+2bUm5omAom11xdiUeEup9U2c0A6QzBjNHbZI8RBXDqMJyf7E1r+hQ/EoWINY3Xw9S+KAPV0+2i0ytQK97X6QGvyaIl1XCXmPlSv51anFjZDsUVvDw35QBlhGIDHPS93uNcJiStSTF1rI94gwcYQ7k9+aNbkZXXMr8psfNu8Q3qeRqSrmkQ/SYd7ILhvece9+TfVOeGrvlD4pICQJiks/OGGE5XQQuLsdr1mXUdxqg34vpCtmc9w3HtVvtJLxPrRQSL7GtVx3LjpIWw/Kvs7tg0MxVXrDSpj+DUjiFyO7g95jJMGySVdBh5M0IHyTnt5xqbHfJXZ8ZAXqfGv+ncEFrYxglls2ghzvHIkV1gmsQ6iNkJ3cUAqq74O9paDM7JV5tMuxMI18jqEsNCISDsE37z4doOXPj2MxxAJ9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: proconnect
    type: Opaque
