apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: proconnect
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_PROCONNECT_CLIENT_ID: AgArKLC+ZQhjgZmnNEBCUdZN8EAIByDlg3TCScxpAy6T3ZgrUCKgPj0D6tBEREVKlVySd/n5/4dPJsVoVovXwQ7pgUICMc7JEV4HfK1SQgmxg+g9U5tIoX9attHO6zXEK3kOeDLYjFBUuj1b739iyj+WqXNvke7uToBLYoO0OuBq+wTlwNuiiIFVKhC7Mi4aH9lt5tZFCu0Td7CynOor5KYvBYvs4aHB/vL2PlmEyQ2F2SN0QBxM7nnKNeawp+APPwWuybul56o+Aqzn0x5vn0jtCw3gbsZP2YYWRjBQzc3G3qVRFLod5cpkwsJevQS2qTToQ9zXLgiGsc8j0YE6Spk+YZPpbUoLQFJrS/KHLirzIMh2+HMg8eHheM4JrrIp+vHAL9cPq88GRhRwESpdrupR75ouRPfVoqwEGcmsRbGwZHwiwPgM9SOLCYXiHQ7t618b/gbAqGvOZZwg9qxc3LPs5r05hZvgGtau8kJIrfCoxEJRoSp28wGdnhgi+TEuijXH+xIkgofKMU7+etmvmJYsB/a9ArDUCBm1zNQsU1QG6/ir/5oskqIr8vhVMeKkTAN/aJ3f5/a9VSqLAjWsyKoYaDQNHOkk+cIgmM8kM/bypY2Bw1zsNOTRRqAJzHNNn74bq0/eD7ujJ7Xc5ccKEYu6yOIXwpB1u5VZhNwn2eI1oP70KJ+dftulDOl+963yAUEb8fGVYFrMyE0Ears5PQt+6ev1jwqd6S+qJAn0NXhRKoQEatdv93RMfvdfoaZg7+FlhWPOQqr4YhGDxEOQgUli
    EGAPRO_PROCONNECT_CLIENT_SECRET: AgARP52R9nDY40xtUq5r9/04Nu/SPYhTiWJmEMmlvmdYsmCyR8pjMVZ9wjy2r4vKfFqER7hb7Zt8Z2bz497UrEFZs7OH6v4dI5ZOJ+2Gd+fVfWUPEK2ViZTTcsEqgoNOkkI0foz72KHnIsEQ4a6QM8xwmvYeJcBd2XoQYYx4bUXoGyOykfQuZGV2WGFmgzSkGLSYDq56m3ighQ0X8Cs8ciwNZq6QOaEqAErcvN0LwaUKfBqts1CkomgsI28pK2tX/CVIE625EWadAwowmmKtoYzuY8r4lW1oNlVwyU5L4F1Ropy0CMjpOI5Ew0032XDF5fwnO53NJBGcYh2RvHFbfJ6uxZ2O00IvvVhBHZjmqbwNW+l5vlldkJhOdNMXcx+k0wnxkJW6VLFBGDf2ayOCF2t+dBooMvAxer3v4N+J7Jbi53J3rYy6O6J4jPRCh136Vtj6Hc8ONmFm5nF4SEW5UEgN3L0JMkgng4YAsShFIA5yPEbRiwILPYRVNT1XjdD1QDHC2rGMmi6cCSxiquTCNdySgIU6z8dOVm73JWG9uq+ORsN0e+Mues0L04uaAklNlHthuCObnFQ5D29GbFmk+DVnmP0jL0fCBnzUfT5KIoTLwXleMagZVaSYCQLNy9fK70BHBARy3zquV6s3eF2SSiM2IZgr1afgJ60u4xR99fn43aFsSAYxPui2zAn2w7nRIun+bSFzAadOWcA+IvKF326d5xr7trkcpNrs3as32jK6TA0XnX7Va0oiNq0jOVM7x5BfwTr8ck7hslQibAM4V3c4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: proconnect
    type: Opaque