apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: s3
  namespace: egapro
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgBK5bokpB3UTuDmFtw8xMdtjF/imLEYpJNhVHLADg/FdGD0xuZHlW8h70+af3aP+3QazEqS8e6AtwbbIkDnoh8LVTld1QZOvGK8RmtM3ie1h1lG2UTwy1QWraRrLsY4jAVBeoS6nHpxgnKA2LW92SaGBsSRANwlEleV3Mtf7cuVk/sa7hroHxDwAApfG5xxEqQR/1yCyWupCJWSaFjN3rlC8qPjZ8PB4hcY92b9By0NvmFBgXEWQqzJdVvghpyHjbe/YUhusLrfJI6xbowJNNl0F7qY8vH0wNlEvePSLPrlZeNvaBjPD2UAW66aGiilOcz98CEATp6/D66HhFCdZ4xVl/SEqLRNcaZrhaX1fJnMybgPI8/SyRPtubwanCIHlQbJZsj3inhnJDgpz8Lg4Gk6mvzzJkbMN/UciAKP3K9RqoX2LUZaambAUO7t1H8J4CdbfVcgl3pr6Id9N015x+wRvJqGxCQA70RcjCE661gOfnUU5xWUjrfn6MD1TcnCRkCv6LqFQWfzTRQUJKnFUcZSem+p1xSUqiMvnGjXWp4g2Vz3lwpuUj74CDwxfU1hYZkyDmtD4ChQOAQRZ8H800e3s9xkQ1LO1vEILoG0EmWe3acZmDpkS/DMvci2Y16m+Y348cKqL2/U9ys+A9s35cWbeXVaVSRbvMWoGKHfYMtvNzfj9GE04X9TMnfJN1Z2Cy58jq3MfUl3GgPfQ4ioRFfKB04L8vO4kvIYAfA3WIBFyQ==
    S3_SECRET_ACCESS_KEY: AgAJrEjoz2aTGcXdB41mfk1hj2n6hANrH/tFZ8h3ruCAzKO3HrQn0VzOnafeID0pojFXzKi+I/FdADA6XHzs13VHjv0e9VgvYNxNa+DRpI8WK+8cPlAzyC9+B2FX/gActypBWJWlQfw/L5ZNScDKLW/xKl/7iNRmayNxEW9xaCyQui6kI1juIBmicjx8RDrwhxBe5rSS7wI2gKILb/Lvv+vmpfObnGAmumooyVZPJpnozBaW0mcdfXd3IGCTK+AVz/evv4tadpGBGNy7JVFF3PMuj4ldYbI1xtrpY7j3WL2LaBoX9BsqdyAPaQTvyd7rhLjPUU3AIeCrmUt+yDfmWlOI3ZllaNm3VaVppqL1Q54d5NgCax1k6DteMNGzBtMCvb7mxaqAdeRia0vb+CnFPqPVACmnruUO45YXqMfyli9SNFjm4S/gIP21ZKQJFzO5SrLG3xpFtwnl8L2sBLAzpvs5c7oVpV8GCr8GAnPhs/7CTvj81qilggxvZ7xNzybUWOo/6rsM39ufVHVAKB0ie0qPDZ+Id+RXwd8Mjwi+aPb7KgDyDk9HoIyQCmTSK3OHgxn4+OiNXpmaVCEcPU63sZ54Lo0bVtaNwkEyn9XTjbFWmMrZfQBGvBY7bBTGWCJxuWTN2avKN4AWkITxmD8oMEjJpezLpk0LjaX9ek2hA4ZwuQSWI/vQJJzEiHFoDaCWVaQtPGvWIMaokvBTSRg6VsCBX3Tqjch866Fo+0JKgSz4Hg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: s3
    type: Opaque