apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: sentry
  namespace: egapro
spec:
  encryptedData:
    SENTRY_AUTH_TOKEN: AgBm4It6eC4StVy5KFo/wkSXK4XZbnrKSyIfqutehHZ8c+FvgesO43Af3AXCCWvtZQgvcH+cR9BT69kvbpSKApmHVo1UxJBA0/A9EjEFeb293um3TypXZF6w2XzRhdUGNI3VUha0T0wMhBojO8dc+Jl43Wvl3KZ1QjYp2KyRWyPcydgO1XiKi8EWdKq9bbjVJkhwohSeyWNBkyQBWSh4OCOKBCgbXliCg3DDjhBTgz2LpZSlFbjniQSmeWrBlZ+Ezc0rkqA61HnHcUfg65twx8zXEhv1Yju0zxDmoeh2NpYg4T3Mph8KErniZyynVsq5Yxaa9jxLNec/BkVUBJPCze/QO3Q3ptcaybV9SMo5ga0E43rZhmfBoR92B+irgW9P2CB8Ik6V0zlpKRRXApRs40NiWsqYQ7qucKMdqaB/vCPjONSSqolk3reGqheHPTQ1SGOBU9TRGz6lIyIszYkQ/dSIRiTaYsHyXajFTUFByVnyzd0Ex4z0mBGTbIdQa/1RsLQ8kJxl3J6IX/toZyt0j7lm9bQVBq553tnrTNfOpSAir0fdzGUamjXhLle+4+9NHt3HELIVrkXvb4LAbhGppA9VNcIDdjdHOFVZGho6BJYrvT1nvS4yYMqqUN+u4IB4YzB8iJjGyO5OpTmjlIfNyQeRBTGfGxpJIS17UNZv+QNS/TXHDFB/GnUA3aqcxklWLUESoIr+pSoh+sT7hrkWl0zhj206Wv1cibOyC2RgWjJ6xSYO/4867YaU1JT58tCIkEMU2F2iKSM5faFRLUTCTHsP0zw/LgGI7Ipns57whB3TUizRqfTKRotpZNy5Q5pYvtD38hRJAePkRHSVRDr6H63ba0w1ZbeNhepUH0SWVZMo0G51iG8QJC0of/0khXsL8zv/D9BxTM1JtWOMHqVRp2j44/L/AOZ0NQwLjzshFZSL4AWI726eFbj9M9Fq1KooQmpDivUQF3gxFl0rrdRWdKawRCFApE+fMoXQhVsxOptwT8YjlSUFzBdz9rxN2TxOjFOKW49Yt0z/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: sentry
    type: Opaque
