apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: staff
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_STAFF: AgAFKx4O75i8IjIuU0Bb/pcQNL0Qz4VEYCNUx1s40C9Kbmvd+LZecv0SlsfnL35XpIer9X36uYKq85uwnQyxhOtnde1BrY1ZXuy6n+H29o4VeGBCFy5DL/2nM3zZH1s72gNRk3/HP+ZTp68ZOF1Ww208rszdTrpJhzD+t0F7jDyIC9kq6plI7BJAgJiWG94rytaoTHyJFeHHQvFWGfl+SOqz7cKS8U+jhtQaJhxOjD7n1zPfWeePv/Yfmfw8aOcnWEOP5u8kGhM2bUjE75Nw+WFf2a6EMEzRcLsdfVVM1vN9Dvps8Ew1/DPQI5gBZC85t5sk4W9l1pLwKu1SjBQ4InBdLj5dWho9IVFZzmpADLtcT8FKVyVSQ+LPirRDzuudPfKBbrhfrxAIkT3+I74OjnXUN/HtyjgYy22Kg+vlf0kF1yEhvX3mEiQK48iKoX2DJE5At0vMov8bGGQzEgIe72GeNioAeTGnZdHQ6xYiafLSICTvt6iuS4ZCkZ5yppIfycL712kmTJkrdTTw5s5hCQTU3OZ+W6D+X7mlkaC+7pZ4E5OmMcg8dw0otNQqRLxrofEWBIY4CuUoQFowoirMA/GMgBgzUDV+bhtHVOIhK4P9FXgu4Gc63uQgLPbfcaXYM0DlnLosRggz0f9PR4W6N/8fhp6+734W+YfZyKl7D2DrfXyen9dDYABnOi9/xQzXrPn1/og/4LgMeaA+geHLNf+1oiVXLGZ44BwZ/p0dvEzrsYVFPQyPhuCohI7uz9O4wkFdqewa2iX5N+T83uxKGDG2Xz05FVIpPLlxt9PfBZz+Ax1WkQ7bdXF5+QgJPv8vjsVe214c4XtvfflsqBPEE6bNybTHwRn0ypTnRPm2x3dIBm8/idSiLMQSDD5UdC5Ayq3uU5VpD2zVyI7UbyWynB9FPT7+dDzGJpqRKY/AbNhVCBxGvb9lZEUosl1Ir6TEJvZ5sytYqwBr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: staff
    type: Opaque
