apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: staff
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_STAFF: AgA0hST83tFLyUgzCss5qYlkdnUwMs3giGgj53lm/Np2SqI2400e3nouBrtRMptq2HwWwhphXaL9li55AxSLnDXqEzF6lzTkJ8rUtVnbKQoyUz1CN+DLzeuTpkioVIFSnMLc5XuKIQI8anJUhTA23WjpyQ5otJFYWxpj3rEEtQHaHPgloMD/KqrUs2PHGJPznhi2MTOcWTJLdmfO6he7QgVakXIXnxaoNq6fqxuQPEj7DNiI7B7E2cELAUOCB4yG4Efg9CYPy/HlOopLk6E0V9EAWR/V+1Khdq0cMteNJBoqgqkPG+92KVmVTFjSzUgVijTuuMQEgKJQ/hZWFtI4l4Oj4Ar/WzumIhPPdhpnDyFGOyue3So1oez4uMxaIuJHouHCUBbSWSfAMT8v57bCGfqU0PVeL/OtSkpjHAOd4Nz7H5gmDYcfmSeZ3fchD0eOJryoJi41cwpDrtfF4sQJAFR9YxEkuBzPTBs0PSfz6AgTvJvYHsusb9CSn9Y0W6tEXY5MVrwbLbrL1nYqkjpXfKftBx9pmaiq1vKlFZbH7HmaUIEQt602+LS5jskMvNbWVYrnp3WImt03oesCY71DwkJ5PxzP5mz4T86dKkMbrSdQEarWBzt4BwMDI+DAMgvt18tKZnC1BwvSJGFSO6DrPQDNs+Roeg5boJ3jBZLlP1YHXlbtEOTpUxdzXKcqCNnZ9DJZNRkpooRKbtNZm7R19Y53yY/6E5ZuWhAuw94Dvv7xFj8mL2iJ1pbg4kCHnb1KWauFz308febZWqaJAXIL0u5Uw1UF+ethPQvE8S9nVAP73UanVTV/0Djk8MmpbmzlwG3R5p/sva+gHE6hGmcK1nTnjnD5DpHxn1EJkvUsBKC0bxb05sRCMqAtvrPRb+M+16cc6XU=
  template:
    metadata:
      annotations: {}
      name: staff
    type: Opaque
