apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: suit
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_SUIT_API_KEY: AgCMO2rNpRM0qOli/ewNI2OAtpiqK9lRXvAeO/HujT9InbrBjfF2GriC411TszJIdDoUIyG9juv3spy79eQOZQeUVBrssnbNzNuup0uYxhG5qm6LqJbSHnn7+CneN4Z1VcpoMpBGeLITlydM5pXAmdaf9o57Jj7zUuxSudMDJY5FrEyWdOhbkqVBUE0tsSPsXpGxSYEKilByZtOirJmV2z2psYSmQYPDdOAhfvXzSBWNJGk/m7HDrTZXLnUjioaD4Q5nRHwj6Ty/HtHwPtRXkeKEomQjFlXF5iCy8Fqu1vc/3QIMAUBO6o5vFNgJYqyuAjNZrKX/RYULmnTYlhe0mHc1C0bOLr3iyAPZ2y+MFXTSBQqw5au1Nm4Fa69ORYOwPy3Li2ftXQZOHbwZJun8inw2bzBJh7Iah29xBUV8o70k58I0K1/AjE1xCdu1egNG41PBctEmEm5GcTNy/f+Ob7Y6dProqAQmylFZBUqYD/dmSzCg1cGGZmrwJsrgEZpS3i+XZOZri/vk8fNCqpwzlsWe5rg4qS22vxuzsiBYuwouFeoUJ+mVd8+tPnZZNXEs5eUcv9IAL0o68vWSdxNfiwxhq33QewIqxv+jQ+jFin5yjTJzZcwhIXR5LxuzujYBCubRClPuSn+qPOkOpYajwY+BDzsJ1RokE1FiFlssAdwecuK+FpnDip1krySWpLXGOoBU8uFhQ8ImSkFQLULIqDBDQoy0X4PapgZDNrD48+OjWcOL7FYeTED3+F3mCR4Bsp2FGSZ8xP27BO3MiecSDUmQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: suit
    type: Opaque