apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: suit
  namespace: egapro
spec:
  encryptedData:
    EGAPRO_SUIT_API_KEY: AgAHam6PdQjqxcVEOXa1KzYoPaxRqAdnQRML1wv7GS0s4C5X8IHPpsPvQKoPuCClkpj54TnhFLpl5qFS2TSqzdC+gj3fi0iO9R8OmNAO6CqSdtNv7vYqRBsksGMw1D9hY+KHrDuyzwkKjl8w0JlBDUjy9fiCrz9480vrpsp7mQTobIWzeezZdbjeJBe3nTiWkWsD9M2sTJS84k97yqA8pwabU0yTW6hIw/MHvM+f+de4YCQTppObprM8L61W74DMvuuy9NaC1ayg/X8Dt4zpjdmLlOQemYScQrRAS72sJ45z4V7ouYmmBEfOi4G4IBjLRZQhIppCa2xFGeFnt9aWiAbCox2q6czGPF+dERhxh1mPFzYUHBpAXHxTehz8SH3qD0GUXgEpPnDRhvw+kPHYn8kPTWwOiQQYZ2M+DbPGMgtRc8Q8imTEYdNTDbj0rYDg5eNsr4yQPuVT5AmzpBJgbOgQZBfODZKLQrJcmCdSJWUSVgH4A34myDSDWEpw0krS1mCMzzY2xbFJQCsG50nRqPWXC/XJZNb/S71MKSaeJNz7dmAxBGjPre1XnlssH0TgiIlGUHhiRGWbInmbqtjjj1kqXZPkF6Xq8XZS237fWdhBuW7MPIQWjx3PtvL808HDFJ8EaTB6R5V3uRgxoBzlpl04XFCq/AuzeGWAPiTfefU5CMOftsjSx6K+FVpQGv0f3x7bSBtU85LvOcBHpY2HtgRrYuGkHEyeAPQOQJbqcxxCMqGXu0oYeSO3YSOXVTmiGCifJjV6gnhj9dZ47B9Atzyd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: suit
    type: Opaque