---

#
.deploy_egapro_postgres: &deploy_egapro_postgres
  image: ${CI_REGISTRY}/socialgouv/docker/helm:${HELM_VERSION}
  script:
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - export POSTGRESQL_PASSWORD=$(kubectl get secret ${STARTUP} -n ${K8S_NAMESPACE} -o jsonpath='{.data.POSTGRES_EGAPRO_PASSWORD}' | base64 --decode)
    - envsubst < .k8s/postgres/values.yml > .k8s/postgres/values-${STARTUP}.yml
    - helm init --client-only
    - helm upgrade --install ${STARTUP}-${NAMESPACE_ENVIRONMENT}-pg --wait -f .k8s/postgres/values-${STARTUP}.yml stable/postgresql --namespace ${K8S_NAMESPACE} --version ${POSTGRES_CHART_VERSION}
    - kubectl wait --for=condition=Ready pod -l component=postgres -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-postgres-k8s-dev:
  <<: *deploy_egapro_postgres
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}

.deploy-egapro-postgres-k8s-master:
  <<: *deploy_egapro_postgres

.deploy-egapro-postgres-k8s-preprod:
  <<: *deploy_egapro_postgres

...

