---

#
.deploy_egapro_postgres: &deploy_egapro_postgres
  image: ${CI_REGISTRY}/socialgouv/docker/helm:${HELM_VERSION}
  script:
    - export K8S_NAMESPACE=egapro-${ENVIRONMENT_NAME}
    - export POSTGRESQL_PASSWORD=$(kubectl get secret egapro -n ${K8S_NAMESPACE} -o jsonpath='{.data.POSTGRES_EGAPRO_PASSWORD}' | base64 --decode)
    - envsubst < .k8s/postgres/values.yml > .k8s/postgres/values-egapro.yml
    - helm init --client-only
    - helm upgrade --install egapro-${ENVIRONMENT_NAME}-pg --wait -f .k8s/postgres/values-egapro.yml stable/postgresql --namespace ${K8S_NAMESPACE} --version ${POSTGRES_CHART_VERSION}
    - kubectl wait --for=condition=Ready pod -l component=postgres -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-postgres-k8s-dev:
  <<: *deploy_egapro_postgres
  before_script:
    - export ENVIRONMENT_NAME=${ENVIRONMENT_NAME:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=egapro-${ENVIRONMENT_NAME}

.deploy-egapro-postgres-k8s-master:
  <<: *deploy_egapro_postgres
  before_script:
    - export ENVIRONMENT_NAME=master

.deploy-egapro-postgres-k8s-preprod:
  <<: *deploy_egapro_postgres
  before_script:
    - export ENVIRONMENT_NAME=preprod

...

