---

#
.deploy_egapro_kinto: &deploy_egapro_kinto
  image: $CI_REGISTRY/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  script:
    - export K8S_NAMESPACE=egapro-${ENVIRONMENT_NAME}
    - envsubst < .k8s/kinto/deployment.yml > .k8s/kinto/deployment-egapro.yml
    - envsubst < .k8s/kinto/service.yml > .k8s/kinto/service-egapro.yml
    - envsubst < .k8s/kinto/job-init-kinto.yml > .k8s/kinto/job-init-kinto-egapro.yml
    - kubectl delete job init-kinto -n ${K8S_NAMESPACE} || true;
    - kubectl apply -f .k8s/kinto/deployment-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/kinto/service-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/kinto/job-init-kinto-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl wait --for=condition=Ready pod -l component=kinto -n ${K8S_NAMESPACE} --timeout=600s
    - kubectl wait --for=condition=complete job/init-kinto -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-kinto-k8s-dev:
  <<: *deploy_egapro_kinto
  before_script:
    - export ENVIRONMENT_NAME=${ENVIRONMENT_NAME:=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=egapro-${ENVIRONMENT_NAME}

.deploy-egapro-kinto-k8s-master:
  <<: *deploy_egapro_kinto
  before_script:
    - export ENVIRONMENT_NAME=master

.deploy-egapro-kinto-k8s-preprod:
  <<: *deploy_egapro_kinto
  before_script:
    - export IMAGE_TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
    - export ENVIRONMENT_NAME=preprod

...
