---

#
.deploy_egapro_api: &deploy_egapro_api
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  script:
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - envsubst < .k8s/api/deployment.yml > .k8s/api/deployment-${STARTUP}.yml
    - envsubst < .k8s/api/service.yml > .k8s/api/service-${STARTUP}.yml
    - kubectl apply -f .k8s/api/deployment-${STARTUP}.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/api/service-${STARTUP}.yml -n ${K8S_NAMESPACE}
    - kubectl wait --for=condition=Ready pod -l component=api -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-api-k8s-dev:
  <<: *deploy_egapro_api
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}

.deploy-egapro-api-k8s-master:
  <<: *deploy_egapro_api

.deploy-egapro-api-k8s-preprod:
  <<: *deploy_egapro_api
  before_script:
    - export IMAGE_TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")

...
