---

#
.deploy_egapro_app: &deploy_egapro_app
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  script:
    - envsubst < .k8s/app/deployment.yml > .k8s/app/deployment-egapro.yml
    - envsubst < .k8s/app/service.yml > .k8s/app/service-egapro.yml
    - envsubst < .k8s/app/ingress.yml > .k8s/app/ingress-egapro.yml
    - kubectl apply -f .k8s/app/deployment-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/service-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/ingress-egapro.yml -n ${K8S_NAMESPACE}
    - kubectl wait --for=condition=Ready pod -l component=app -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-app-k8s-dev:
  <<: *deploy_egapro_app
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - envsubst < .k8s/certificate/certificate.yml > .k8s/certificate/certificate-egapro.yml
    - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}

.deploy-egapro-app-k8s-master:
  <<: *deploy_egapro_app
  before_script:
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - envsubst < .k8s/certificate/certificate.yml > .k8s/certificate/certificate-egapro.yml
    - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}

.deploy-egapro-app-k8s-preprod:
  <<: *deploy_egapro_app
  before_script:
    - export IMAGE_TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - envsubst < .k8s/certificate/certificate.yml > .k8s/certificate/certificate-egapro.yml
    - kubectl apply -f .k8s/certificate/certificate-egapro.yml -n ${K8S_NAMESPACE}

...
