---

#
.deploy_egapro_app: &deploy_egapro_app
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  script:
    - export APP_URL=${STARTUP}-${NAMESPACE_ENVIRONMENT}.${APP_DOMAIN_NAME}
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - export CERTIFICATE_ENVIRONMENT=wildcard-crt
    - envsubst < .k8s/app/deployment.yml > .k8s/app/deployment-${STARTUP}.yml
    - envsubst < .k8s/app/service.yml > .k8s/app/service-${STARTUP}.yml
    - envsubst < .k8s/app/ingress.yml > .k8s/app/ingress-${STARTUP}.yml
    - kubectl apply -f .k8s/app/deployment-${STARTUP}.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/service-${STARTUP}.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f .k8s/app/ingress-${STARTUP}.yml -n ${K8S_NAMESPACE}
    - kubectl wait --for=condition=Ready pod -l component=app -n ${K8S_NAMESPACE} --timeout=600s
  allow_failure: false
#

.deploy-egapro-app-k8s-dev:
  <<: *deploy_egapro_app
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}

.deploy-egapro-app-k8s-master:
  <<: *deploy_egapro_app

.deploy-egapro-app-k8s-preprod:
  <<: *deploy_egapro_app
  before_script:
    - export IMAGE_TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")

...
