---

#
.deploy_egapro_memcached: &deploy_egapro_memcached
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/helm:0.20.0
  script:
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - helm init --client-only
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - curl -L https://github.com/SocialGouv/helm-charts/releases/download/v2.11.0/helm-just-linux-2.11.0.tgz | tar -C $(helm home) -xzv
    - helm repo add socialgouv https://github.com/SocialGouv/helm-charts/releases/download/v2.11.0
    - helm just fetch "stable/memcached#3.1.0"
    - envsubst < .k8s/memcached/values.yml > ./values.yaml
    - helm just render ${CONTEXT}-${NAMESPACE_ENVIRONMENT} memcached
      ${HELM_RENDER_ARGS}
      --values ./values.yaml
    - helm just apply ${CONTEXT}-${NAMESPACE_ENVIRONMENT}
  allow_failure: false
#

.deploy-egapro-memcached-k8s-dev:
  <<: *deploy_egapro_memcached
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
#
#.deploy-egapro-memcached-k8s-master:
#  <<: *deploy_egapro_memcached
#
#.deploy-egapro-memcached-k8s-preprod:
#  <<: *deploy_egapro_memcached

...
