export type iconClass =
  | "fr-icon-arrow-left-s-fill"
  | "fr-icon-arrow-left-s-line"
  | "fr-icon-arrow-right-s-fill"
  | "fr-icon-arrow-right-s-line"
  | "fr-icon-error-fill"
  | "fr-icon-error-line"
  | "fr-icon-info-fill"
  | "fr-icon-info-line"
  | "fr-icon-success-fill"
  | "fr-icon-success-line"
  | "fr-icon-warning-fill"
  | "fr-icon-warning-line"
  | "fr-icon-theme-fill"
