export type iconStyles =
  | "fr-icon-arrow-up-fill"
  | "fr-icon-arrow-right-line"
  | "fr-icon-arrow-left-line"
  | "fr-icon-user-fill"
  | "fr-icon-warning-fill"
  | "fr-icon-success-fill"
  | "fr-icon-error-fill"
  | "fr-icon-arrow-down-s-line"
  | "fr-icon-arrow-up-s-line"
