{{ range $job := .Values.apiJobs }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $job.name }}
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ $job.name }}
          namespace: {{ $.Values.global.namespace }}
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: files
              persistentVolumeClaim:
                claimName: files
          containers:
            - name: job
              image: "{{ $.Values.global.registry }}/{{ $.Values.global.imageProject }}/{{ $.Values.global.imageRepository }}/api:{{ $.Values.global.imageTag }}"
              volumeMounts:
                - name: files
                  mountPath: /mnt/files
              command:
                - sh
                - "-c"
                - |
                    set -e
                    {{- nindent 20 (tpl $job.command $) }}
              args: []
              envFrom:
                - secretRef:
                    name: "{{ $.Values.global.pgSecretName }}"
              env:
                - name: EGAPRO_DBHOST
                  value: "$(PGHOST)"
                - name: EGAPRO_DBNAME
                  value: "$(PGDATABASE)"
                - name: EGAPRO_DBPORT
                  value: "$(PGPORT)"
                - name: EGAPRO_DBUSER
                  value: "$(PGUSER)"
                - name: EGAPRO_DBPASS
                  value: "$(PGPASSWORD)"
                - name: EGAPRO_DBSSL
                  value: "$(PGSSLMODE)"
---
{{- end }}