apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files-restricted
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/satisfy: "any"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.whitelist | join "," | quote }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Identification'
spec:
  tls:
  - hosts:
      - {{ .Values.global.host }}
    secretName: api-crt
  rules:
  {{ range $fileName := .Values.files.restricted }}
  - host: {{ $.Values.global.host }}
    http:
      paths:
      - path: /{{ $fileName }}
        pathType: Exact
        backend:
          service:
            name: files
            port: 
              number: 80

    {{ end }}