api:
  vars:
    EGAPRO_SEND_EMAILS: "True"
    EGAPRO_SMTP_HOST: maildev
    EGAPRO_SMTP_PORT: "1025"
    EGAPRO_SMTP_LOGIN: ""
    EGAPRO_SMTP_PASSWORD: ""
    EGAPRO_SMTP_SSL: ""

app:
  annotations:
    oblik.socialgouv.io/min-limit-cpu: 2
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: "staff"
    - secretRef:
        name: "egapro-secret"
    - secretRef:
        name: github-oauth
    - configMapRef:
        name: egapro
    - secretRef:
        name: redis-auth
  vars:
    MAILER_ENABLE: "True"
    MAILER_SMTP_HOST: maildev
    MAILER_SMTP_PORT: "1025"
    MAILER_SMTP_SSL: "False"
    EGAPRO_PROCONNECT_DISCOVERY_URL: "https://keycloak-{{ .Values.global.namespace }}.ovh.fabrique.social.gouv.fr/realms/egapro"
    EGAPRO_PROCONNECT_MANAGE_ORGANISATIONS_URL: "https://keycloak-{{ .Values.global.namespace }}.ovh.fabrique.social.gouv.fr/realms/egapro/account"
    EGAPRO_PROCONNECT_PERSONAL_INFORMATION_URL: "https://keycloak-{{ .Values.global.namespace }}.ovh.fabrique.social.gouv.fr/realms/egapro/account"

keycloak:
  enabled: true

maildev: {}
pgweb: {}

nginx:
  annotations:
    oblik.socialgouv.io/min-limit-cpu: 2
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

redis:
  architecture: standalone
