apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: api
spec:
  encryptedData:
    EGAPRO_WEEZ_API_URL: AgAcc2H0vRbrh8KwOw8oAU3KuCbGyy6pNhHHffIeKNeqFC3IDCSkvm28/CueqH3W/3nOp3u3qSLmSqPVUvcyneMN/svbkys5N8Ls+yMbHCUwLjUkasCLR0pR0n1h22YV1Utamrp23TlEwJvMWoQTKXOWZ7LiCFVdxQ5FqGCnBbnlI+LXSLi8MbLndJWbeTbzd1/CkO0fsXFlT/avPwxD+Ql80lr5Jmu7eZWY5z/MYV3jpG7HJ7agsN8p5Cs6DmuR76iDtr8EJJK55xSUJbc0Xm7N7nWxI2kz2r9dAs/YqSQ72vlMcSQJ/eYJWEihEZyrciYDznAYzbKTWGG+rEHyneMufAg5TfVT8UT5SH6pz7qqwYmaJYPJMDCXvu8YrBGJ8orQShHKoWLHv75X1MMV82+BmplngudCNu/ylHjXPsxldD23w9hjnAmq9w08JzjMcoY2CefTr3B3GnjpPOoEeF5ZD+F3XmpUO9KUhLOnxQpvPLAaA8sIdUEBzQuxfAL+aI8q/NsfunxwgOq5e+GKgMwKMUrmlBw9WZO3KVBQjfYlHFRu8vIQ8BMQc1z+Vdj5WTVtlyNbbhpyGuFb15jmZ/cB6HRvCtq/Sh7ntvmOX0eUlI2IP9Tp8yoV3U932kWcZGJub+rEZDtj3+V5McFzS09T5iqp+G6BAQ/QV6QwEZRn+KTcDliaXO5udRLHoY1LRaFU5s39xISOCnS8kfpFBmLPPcPMCeryWz+7CvB9ueMiKj1FVW4r2Jjo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: api
    type: Opaque