apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: audit-cleanup
spec:
  encryptedData:
    EGAPRO_AUDIT_CLEANUP_TOKEN: AgB0dzT0Yq5QSR0VdtFDKwGdHBcUvORdMWe1EC8M88Ayma3x988mJMKJu/Je2YQuv01jUsj0vOZRGav/hs5AsvcYFfQqR1oyxlZeQjlMrmMjyOMaNZtsJB+YYqSbMcnP3MwvpApCeW7VNSLe8vugftx62ba6BIVUxnPN0PII0/igkV1/C+FZbQaEcqCGB5lp1I6w1aH6C360hb5/tL/dTjMfAYSyA2l1mgWM8Z1UcG0UVVhn2r2hmZjyZGHkK7hclfUGIzMj0DN8ZlzABXFckwb3ajPC4qkLZUKN5nsyxv9pildmpiWMqK5s5nYnyUuHUJL79rxjWXVp1WG7Hak8y6QZjVyTXLARMYpAZmZ5KVRCQVJKa6v2NND8T2JMmI+WEPNOlsiP8LmEoFBZQBhnW4II9EHJ6w40afLZ7TYrXkjVunWuAX6frgkitxHL4YLCqBKwLf8uogQbs9HhKYHOJtTWHGtukeECH9fjLmP8WMZ6RjuobJEKfSb1oe9yAJyVkn4caAN71fIGJgmmI/P/0WQjhFOkQeebmwET1yZK8smahmp7QGzu1cJnAGE2xDUODHU1ItNhVNYpslP1+lOXdoPoHyZTkEk26Y3gLAwqboDts9JI7Qtgv3+rh6INcrt1RBbZWq/LoUIyQQrQrn0/NcTksrwK+SfFWtqGpprek2wE+7LRhRF65HWSairzSG9+OT9oWtNunbOhYI3gIxwGQzvAtC3RvUgqw2WODTbOg60M/XJWQ5MBo485l4tT9JrJBrQom4rQh/3kctM6Rc5Mbx4p
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: audit-cleanup
    type: Opaque
