apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: basic-auth
spec:
  encryptedData:
    auth: AgDGMigQoy6ew0tPK1VOy3lc2TDfybWVLUovSzvW9JcuUxhF5TwAfrZbMqteaav0HEM7/gvURT0VCNb1gEUdBJiyyDRtrMziEMif1yLYJL9/kdBZSG4WyAkT3uSU7xFU+6kov1eujaQOkbSqDzLyvrj/+jsImyCJMtlrxIAnlZ1tA1oQhHk3C5juV6x0u0GEk8T2lM1dQwCScsY5OlMiSBlqQw24Sc1rnhiY25fStH+BCRiKRPcNfcqQry+5j/FLKTqits3KqK0pbNZi9L6C4CuRp0njjoUOSm2Nks3r0o3mYoo8OczgYz1+9H2tvZgioHuhASjvfMrDmZ98zjs7pc7jvdyBr1Udj1x116C+DPuBqCN3/1Q5b2UaRbx8HHwm4G1sROwVRs8udLSE9rz3boQtB+LqA7ZDCa4wxfiK4fdREeujw8ppmZ4o22xOdIW6q6kdUjLseYoRM/9ZCPyzRQWuu/IOdMHbbD7p7xjHMPxqAuv7zGsxHw4aRnajvSqYtNnFVd0XYwQ3A1Gzdl9L6wikFABFidDSQR3WH9hpnKvmooMIwQxTTlGVv52R07eEUk3NBMMWps6NYZfMvMic1M5QV5JgNECqDQrIIlcVl04a8s+4tnKERGHOVzoYOAalqq8SVJp6qieOGzo1vG5H4d+5aFrxLkXyGjNec5yHZkACQDGvE63s4KmaSJoB7k/sw+EnScwQSlHI4yRtOFK+7nMHLq8XZVHltFhRmpr5sN807InSKYpDwPR48n+LKNHS9Z+WBAl/F3M+mXrbK3s8ywwf5g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: basic-auth
    type: Opaque
