apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: egapro-secret
spec:
  encryptedData:
    EGAPRO_SECRET: AgCyU54zAj9zir3k3sQUVsb/xIkA2/svVjkL0MdZn8YKgoaYY1LXQV7Hd5B+ECMHbT4gvF63W0xexNMSoz/oRnTnehg6yEeX+Ppz1OXyalxpi6aADBxj/EijqyfuSDVMdcz4g5VnakOYJOwwGA19Orjldoc14rssEdZqJOH2vyoBh9x//who9PxasLk1j9ImGfcvAV8DjowHFpR56nh5/BdCXzF86xg7+vKYXUTrIDIkqHnwqcDf50iOoQVq0sNG4d6tBYT+ZEPzQxjx+NTQxqnxICauTXYDVDLvplBSweUoYaRgx7ilErhucGFrxJtB9n0p7BdNJM6UcUZzDcD4Hbp8G21fv15evezGf3eEgBkBlBnp0T54GBz7vV/w6/2IEVeh3N8RBc1RgbIkBaKi2aYflvJrawwRjneKmy0jlkzqhM0porwS71AQyVtEIT9KCgHAZamdPZb+sHfC+XIRo7yw5nUAXd31nwlJE14Jy9Qw5guA0L2TNBuXqPEegViSNL08c2X/EBE9DaP8jxLNkQPFqep/cD6IDef9eyTADG+//cBbtAu3wqCaV/qqk5A47tXeGE561L8AAqB9YJeUbSPpGyYi5fjJwadwFY34FPJJv5pMQ1r0t+73nI7r4R3Q8Hvvk/kNa32bh0lI3HuGxAbFMY6/q6UYVVF7PCvsxkwAlVXDVt/So/sfaQiqKKy8Awk3n5yZi9CF0wYmAbF2uJFWCA1gLgbl3J/JxHIawAcFIXiuQTgv0wyxsWh9CRcgCUKsFLMSaZ5KlcWWzXkWvxVO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: egapro-secret
    type: Opaque
