apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: export-api
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgPLACEHOLDER_A_SCELLER
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: export-api
    type: Opaque
