apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: export-api
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgBDJGz3svD6rooLFX0Q0jlSjMgotLS13OL2LOYmcXPKqaepRtSsDZpyegvdMizWFMqzla58B8y8p4yAHQmh6zlcd0zY8ikmZfGAKFxtfr/cDOdTmGX1RiWY+O1tvvZJAJW8rrL2Wx71etz5s+N//HVCEamaMCsFqTHQci3CkBWm0zuG4IEL9lNw+I8ZWakS/Zl2QKp2kjp9jhDbE6KnzkBjMoqed0ofPTiWF3l0ggvJy7Hp82krjrBohh+W6/Oth8KobHodx/YyusDsRttJV2K58EAB5OYg0sL3eWOfFJpiIbJf969CNgIiSh0/4sj2badVqqnlU0Shujp3JahCGzgHP3IcPl3jox3FatXLv+oYfO6KKvd9iOlru+ZAiJf58qUtdL13aG9rXS7h90qlnGbxDveJrQEXdZDinSNa4diz33AHL10SA96JSYhSbQIfGVAcMDrnv9AAKmhD0cRPPUHHFO5iMAXW5B4jtGciVeSJA8Yzl/nNuDexlaICUny/dpALWhET3FGoanJ+KphErRsNBaf1Gq5NemosVSElHmPqI4sNoDIZ2X6PVCJEaiUpex4ZbSu+t9k2MZQxPG+aOFClE4GwiIA3i2RVJG22PHV2+zjVy22S939B/9nprXlvc+cU2IeUAzj/Sl3uvM6EFI8BePQBQbZFwclzFFefTtJEm/aJLZtOkGLhg0puIQOwFHAP7AUpMbepbANpekQHaSE6X6j3txBMEKBGb3u9zHVUew0kC0WfJSG64C7QmnNrcT0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: export-api
    type: Opaque
