apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: github-oauth
spec:
  encryptedData:
    SECURITY_GITHUB_CLIENT_ID: AgA+AbOgWEHzEUOk/eLFX0k0dkJ/qcSVLmKl8UBumiik3GXezdJpYlS5docfJhkfkPLN2vU/FZLVOWcNTFADqoGNrfYmpd1mgDHR9AWgdJrIXyDLJzBbYY4vDOBUohoOznSye/OJ6erxVLG8ibjHEv9fL+RqJO87b6r0n83zuI9cj99sEwhizeGCOFYVD7fHbUHQhaMn6OJ5aPe3siXC6L4uOOU6GNmp4C3Ot1pdyhm/AwSbvTFl6PWG7+VbZHBQJD8+HZZkGjgONFxDUOzXykbpFKMvunTxUuNYiaLUgxy6qj28m13QqXIl0oMF7xcGfmDm3bsR0P0wfKrBdr09kLLm1gYYAf5KgJuvEBuuO5veMVejg0gxTS4nuai0mNRrWxujNjjGk248x5RmYCZpX6Zf4vtOMbv2NcbEdrjFQeXg1QH70PRdhuzupChIG/gLkwbzkOkHZOcp5O31Eo0OGrqDjYXgs6td98zlnvcOoW39cWSd8ZRDKZr8zM6UkElyxZb5nqdR1HSiFwCNrvkdpPabh4kMzwV5Zesnk3xonRDrEoOaVWUeo4NEJYPLpMurjYVBRgmfokSS+QEkx+9MokiAwhj+URv9UkWiWMzKvCSK30zGB6e9sBJ+NFB3eXn3ySJ+crnjKbrKG/xQ8is9A/OxrCSfrnOO5KbaRt+IiI60IcDOhQsc3VKucRNHbfpEBt1D1m4ZqJq5TMGG/rtSBANlGAp6ag==
    SECURITY_GITHUB_CLIENT_SECRET: AgAN0zxbnjdlk5i/HoU9RJhZ6YMItiXI5O59lzvRTPMvVcslAHldS23yP7VAM5ccwgFcnJJz3TCudscyK1ER7Yt5EetBgR4gSd/gGegrxPAB9lCg7TU2GNEvL8/j1tIhTu84UX5FfxmjEuOUppdMtV5lQpAhkqymo5F2raph8hTsCP9ULtJRzdOPtL54GgSxnE6B1L4rE+hlZ72XkLXuVXFMA8cIWkz2gh1QZDCTZrt1CHAfsEcQVpb238r+jCXp6H/DZf89jzmmkQKhsVgk+4MpGYpETUa6E/nUglBiC1Lj12jff+4X91rNIyNBTX4gNXWzLX6H7llHB/lpqHj0Zf/tTiVM7PWpDffDh2NkXJIWDmd5nndPTdr5ggwfxJQcZrH2/Fy2zRPDfzuv2dPN1fTIhC69GhlcQckSKInm2VA2k5Cmk3ls7kLBosGfoxSRCdTmse2OiDpCNKigN5O/0CjNbh3hqhhI5HDkqXBy+p2nybPPR9a7atN2OzKD9lAEHLY9DuzVV98PotsvtOu5lm60yZrsOHaZd32/GGBwi0lc24ZWHs6xJgrGwiKlyflACUv/fGJNqOx+S8gDornoE/kpGIZkaz9vRyE792sxCLXj/lHQsismrl50ut8P+qZPRXcf/XMDGlNHR1o6nBI2mNZjzlSL6azWyNddONoEXMeDYGfVhjXBU7xy6tB8Ba9+K5KRgTXRiAHP2uFtVakLBbwmndu9f9FqkujkvGxSD/XMH0TeqlJiSOth
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: github-oauth
    type: Opaque