apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: github-oauth
spec:
  encryptedData:
    SECURITY_GITHUB_CLIENT_ID: AgCGK2WMnozc4fGsnYpzMscQ1xDvQ1cljRZVgEpZ7qqsl/DKzkQyuXQuYNNQ90HF87AlFT10cjSdkpx06Wi8RNskqrWVA1NH0c42BFKLMjQd2Q9vE+r7zP913+/8CfSeNVf7uAN0pyQsF/SLz0syTvtkz753ydVODI2dsfAjr14A158KRPqlGeM1FdNnXyOF/F1DNa7h2/JGheqejQEVhLDZzpEiFXplUAc+oNfwMek9NNsMF2fy6I5xPK+aBnpni5cU3nsv4ZE1ibWElsgg9gjyRCo5YUhKVduGhpeW4/es8XCHyyee48gmpCEpH9fyJRbkU0meNq+J/VyD/zJcPpLckx7sH+M5jUX9Eju2q3GMXsVdgv+/NgPpPu/Yfey3DjoV+qFdtostxRJADNicYH3Ssoohl1Uq6A6YrLGJrdTedUZU2sIY4fukQXY4iT8++i5ADjscDRffsIREljexzK8FUru/eulnmoAKipTHXoOV/gmrOm+tV7pSc7LWbMUuH4J+eW3dhQ1WAiChrfZgwuiCsMSnRqK7BELnVqae2b8gm48HEhMuj+3ZFI8skaGR/wiDEKp+yclt+Ek6RB2e/2Ovnl+AhQo+MDRUo9qIKP6n9ysB35qTUXMbfNaFyRXsRF1dFp+Upa04iuo4QR/5rzVq0+FDmVS9NjTLtg9XQm0opOh7MjXz8xk9TsORxqOKsyVTNnUPDXE7GkBMF1J7hVYYLZvRhQ==
    SECURITY_GITHUB_CLIENT_SECRET: AgB+F5HilFQH0XkfQfLo6mQfycirc1BZ2trCovv+piv1JzTmtl068k8gzbdTM06Kc2blfrik3i6lufTPlaFnsJIENYH2Lib4Z0b5PbgeU0qq8ppfi5+LQGutxzQ9goP0hN90eTGt3r/UzL2bNJBDcMPtyEmis3c2mkJjj3KzucM1yxzp6TCJoBmL2hL73Cm0IL9jqbP0vvVO94Qb+k/y0e8ew7h2YOyydGA17CyIbVOhfwWIth69hSzCrBW9fSb53amVYg98Tm7Urwhz6S9ZRnK7SrsMW7VgOiBRxHEyjy775cEOn85aQI3DEZ6pA2hT4CWsaRJo9P9Mlx3ecN6Tye7QZYCpIUEagXS3mh4PmbI+H6JxzNC+wKS2d/gz1yM/GYfh1LzMlXO0rzKklqPvfvZJ6WpvjZJHSRIeuGnBYg0mZMIA6XzBIZ/XqwNbP86FXULZxDLuSQOq7DGGv+EyVL48dgTSra4Cyqj2A6poIrD69urn0n/pmFlAGcB20W3cMTGp1GgajVopfkY2hpwmekQZZyxm2x+roRLyc2QjOhDI4QW8gWKoqf25n0u/dO07x19umhqFBAZHIK45c8r8Bpkn5CA24CEWqLCUj4sATHht841C0AfUCLQv7drK8fmR8GB6UJpByWg58S1M42Jg0pGvs6JeGZ5TbsyTUcL0WL552RY/QiuNKpGSSm+H3yw6mQuRXx32xiTFwnuDhiEiMN8LR8B7KXzcz3Vj/Wgz3/bwbt0YGLHoLQTc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: github-oauth
    type: Opaque
