apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: proconnect
spec:
  encryptedData:
    EGAPRO_PROCONNECT_CLIENT_ID: AgC4fCFYNasHvjTjzJjApTD+bh/7O/vmFcMwYbxnPzTDukk/aVupHq83ZGWfnLSFjrnYc/a1IjOcfCyAqUddPXcxzFsw6VAarkPRCWmjmcRHrr18jofjo+5T9h072o4OhTnpqUzwtQQYu80afpKulT8CJMZIzg0aS09E1XKIanvQKEjph/gKq2kqtlivT8p/4//79lVbJDQEpZ/fvEp0fi8+5wXry+TTCEmeEHIX4SAhkf9xK/ocXDWMKPnyO2QEcAJqDD8LMjFXgu3Kn/7BWNlQs1Uyhb6VamlCgke/eLmrdd5+YasqvjrjQjrwurP6geoS0PNQzEbxOvHYLgeqEJje0wgc107YfeQGlel9SaEqaRmn/KfUMUcC7u3O+FFZn/nXZ4gdySFqW5LlMB+c4IaNgkDyEceZYkJIe9DiY+nzp/p4oca4uWOFMHvrUQYdzpNSgbfRIo/gmMEcwSyrStSisu6e6k2GiKeju3Nf45DowcMdskucd1QFtSpfhbrsAlwnv1o8PnjEgqRHqB8XGyByrzljxFvVf2DrRFNX0vHXjlm1s+xf3z1CigTzVu96edmd+bsF9nw0IWslYdLh/ebszZ78XROmq/n1Bd5a41DlHdWXPC8uGWjjHthU4szqZtd71Kgw00KN8eTBQyWJ5Iy+pmcD+VESk2l6LvkKqBlpBbVEjx0f+6p26DD0KGenRAsgk564E61HBPVznkza8LAoKCJei/HVUOobxDv3eeNzqYFf2As=
    EGAPRO_PROCONNECT_CLIENT_SECRET: AgCBiqzhNxG5lfkA/CGv9PiSUcv2M8f5Y/j5fNhQTIfaXhNZZq7P/6UZSG88O6QKcIyJUXww3aZMk+jRYqUld5kUCm1+VwsJ2JFIUprCYzs6+oOyBQgseOiHtIiSLasBPNCeyjTSDEPUyDWgCxBG0aCuNrFiuzfjTJ1eN+h6l89EAd1lj6wf3QyO+bkXjTGX/TPHqLHq59VM5Hjhs4U4xoU5QI3I57sBVxHS9LBXwzEgF/vMpP6yLHLlJghe7+tp0EAeTRXKry+XyqrIU71GnSpA07yJ3blZtT68s5g9CkT/RDQV+3EMAXnRyzJZ4+fcrEDl9yWDRWsYJY3Bu/zBV+mLbk59siyeeft294qLZODXMhAAQ8FhGtVSJ4wFRzETaDnZEIasO7Woy5xV2FctJEpo+XEnNz4P0frewYuHIysDyi0Oi89QymFb6hTRVKpwmBRmL+Kn++ms/FBk7jbFoI8WNuYybCQUZU5y7iNAjkMzYt8niV6ppAqXT5x6ebOODxNUjVdYsMVsP7jXTRmwjeWd9pAuVD2DyLwYKIJ+2iz8qW9Hl6ccxf13ip/0Q70Lfb208n7cJU7wv43MKK37k2TNLLzMY2emNeC1RixZA088hnOnmKQt9SdFgeC9yRaoTT8V3N4StEfVdk6mZGzZAGXhnfrEanaU/wsZilCZV+APcBIqIJOkNb6fqVw97urx7xRgDxcbjG3ulWrdsaYanSuZ/v9SQ5mVnKoaoyAAsn5iVpCyKW8Bn7UWzrxfq5BmhMtqxqUZekh5QZBa6e2YwM7D
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: proconnect
    type: Opaque
