apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: proconnect
spec:
  encryptedData:
    EGAPRO_PROCONNECT_CLIENT_ID: AgDJftjwIBWoiWN3Posc40HLJgtQQC2kAiKo+A9d4qu4n2aQsOgpXTOC7qLOC/5usJzVW0YiC06ByR+WbLCRWuI4O2a/CxKZKxX1SAP+P37qQwp23WeytFmCN3kjyElgjiuKnYQmf7wv8wujCXwaQu/jgTl42CU0B8gB5I1H81AKdmh04qZBueHXMAk2T1FM7lzETQoGrrLCSyWAtUWayoXly7GH+8GbXi5HuFNaNcOIjXznFi/k6ZtG+vct6ycjahhwdfNSOqHAF8jSkuvBf2Qw4IY36uC4k7wfN4j4goHB+etNI+6wd4XU3sIfRUNdpotPe8kXpCnWY4afdcFsJRuXMcqx+bzH6Oj9ayTXvOO8WsxkWKxwnpgAwl9jPcORlZwqfODbGTz0ZC12QgLjydsAHph2o67+0NxC/2q0YdU5fZXLmzFosR+V7gc3HAUq4ZTpxI23BPkP4apZ/vr4kf1GlPayC9X0IDT9+uJHvFP3+yVCLlNI+HPaitMmayG0cLuEXi38UahT/W8MAkUzeH2d1TIYu/sdUMMJCad632w0MakdTMU7uTDYM9qPAPCeZTOY4nKNLp0a8FKwqU3ImzQCPi6fNtFM1ko0pOGLOyhVew6QlyeXTV3gWCe+Dz/7s+feyWifLWqoJap9b9GYz/dOnk6KcDunoECbFMpxAK5hHqF5kKtP14Yrr1ujDZQ7o3OtUNh6cy8VHlo7M0R147PPxN/8H2QTlWtUQSLKHc6Ot3iKMnlk/jAEDr9m19cvN9Bl8Hf4JmiD4QtuGBA43TCQ
    EGAPRO_PROCONNECT_CLIENT_SECRET: AgAnYS4arcX/qigUHK/ayCzKx4UW43FrpLq8RxhxBPPIwLhbaRgynkekW896HP1iYHm2qdoUmZYBI5MOyLsOwRVw6P7FggSJ0NZdvOR7q0s9SzlMKDWi4s9ugoebFnueEnjNok6otXRdHhgypDBZvY3T6xmVDZ36XG7xWQoFU+jAueDGtrwcpCt6H+z5R2y/fHKPEkD+/18OrUKtpfAeCVx1y12z9lipkRjlvompnUNNZ6qFx2dQ4COOD0dfOG0zRMCmgY4wuZ28a+EueNQ7NWwq/bxdbbu53hGkC2JoYlMnw3IA9WBpu7dJ2IXjTC6F0hkarM9xNKoMPgzjSnx2fX4ld3/cZizjNye5lLgFfBSj1CLO4iN5VRznBIVfPeaQ9PjSP59uDf0TM7pG1/8tedetucGkghE6JTN3uiwn3IvfzGsuzd4P6WJz3IAjIdCMe6YxKlrq+YMAPIirfO1jC1YoN8cvTyuUqSFcjXGSJEZ+Fso2IxJwlglqcwHfjciVwwltb8SLBOSor2pu+v1ETfIiVk+KmxhdUTafP4UjlYXTgq/GWiVeZ4ym+8MSmGaiLhs0cXXWH2PZFQQi8cutqRB6m/klQpF7ak9jetH4z5Ckc8x0B8DdRisOytg9MJlb9pmf95agLTNKf8NGhyWirdaA4dEaMh7KWNBtIPFB40nhbHXZSblwk8fookeVDR0Y+vEqdx1Yx8knWVi5R6yUMQmectqiTl8eqsgjJusd4JNQVVS5lJ2tv7+DX0uC8xhJ+JjThedxmpzHmjOi/WO/RBur
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: proconnect
    type: Opaque
