apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: s3
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: TO_BE_SEALED
    S3_SECRET_ACCESS_KEY: TO_BE_SEALED
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: s3
    type: Opaque
