apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: sentry
spec:
  encryptedData:
    SENTRY_AUTH_TOKEN: AgACImQ+v28zr3JN3CMpAS4G3c9NUqai7Vt26zYqfGNdK+uDK9OEqYP6nD8jjQgZM/7xxb1nboq0PJwVqFKYB6whg4Tu7JnAvCbOAkhYGaT/2aRDLY8V0YJ72cOz7JsUeDWOpnRzjapnYF39BWt4fqHCXFaflHodea9BveAZI6/BviInGCLyWiLMovu8TbScgjq2hTmj34kLwKzAx4hMj+sBOX5cz6z9CFCRz4Ee8qFdybl6osfhfxlKHlj47zmsqxDqDzBMaOqxn5LPHMXfgDEYqD1g1TJ7zW3i0ZcDwm6qdhoorRCLSq/+0lOhhyLpcrvRzs0FnxXSuYePi0xvAFyBLhgFw4dPisOvFj7tADOpS6iVLYRgzRcCwSfGDHABkSgbEIZnkPHMb+Uvu133EUOGVep55bK4VaP7GN6K5fNlVZ62G1ijddJufieqcYH4hDleBSVKAr71B5m8c8ty8j0LH0CpbAuuLLsF2uJTdzH807sFy6Takg8bBMFMunSN00K6aAh+7AlO2asYKLgq2d2eL0cDG6YdfShm9kHJSUCsRSNI1uS4I7H6n9ngLxrWzXPdAT1OeK1VKyVF6h2XrDs+ImaSEO5lZzOFOU9ZbUByZ4pPUsSw98L8JaIWLoMerblQ3f6jBP80MG/Wxyrl3xllvccR2TaczKIMMgwmN1hXGAssb/ZoJZ+ZDhtXVoELLTjK5WqMWpW7G1ZEpfUqslM8HOARYr1WC9TUG+SVHVntb2unzz5XvOxBZyunGDUzEU+k6xNIDhswzREPauQF8d3XY9X3qdcJsNgbTsrnsDHuk9Y1iZGVMNElO7ct6Ei6TrKlkwPmYzRyObjJdi1bo0LIIzcBx1AhKlt1DkdmtE69Fk+zN3FF908cm+jSSD+ka2o7TzlKhMa9P6EKoMceD8EnlhOf07U5hmCwPrfEdDxqzLL9z5uyvVhUFl9yfiY7cZUNKd8I9pXol0sGI+XIFijPDyeAAfZoZTdMPKeFNLWKGpB1sFsIcMy387ZL4bS2X3fFOkYXhA2E
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: sentry
    type: Opaque
