apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: staff
  namespace: null
spec:
  encryptedData:
    EGAPRO_STAFF: AgAGJdDBmZApQUVXVyfCTAcjI3QSoyr72nOh5tYA13iIsbemyyhjie6804RadxG3/4Tr8OHo+vFeKBIntYBMqDZ+0KjkYId7r1Zqf8YImd4hR8NJ+rYGH1AN4c8b7XbGpkZ5pNn3pW3ulGqZ5N7aX/JE5LA8JPVwTwHNcNV93d55m8g9rz/PrPLrrRemqKXxdesTBDc3qw0K3ZJfIf0ONe0mM0QPpSsXoGi55czhtQ25ACrw2bBoSwhidKlluXNWhKOKOs7pM6/BBNGHbc6N8WvZ0G9iCCuGE6FGpSwU33ZVy0tl/uCLRxA5svjFQh6LwLiGGb9dwXkH2JOko3Ib/qQe55FzwvFAWKiGnnvC2Rw9xtYPHNWExP3P/ie0tuPzyzV3MxQA7EQUxs8C1Hmy2B/jbuA/UNXu/jm26kYSoVOgvvl9R7Z+tVbXadBAzunR+eLCa+jATFXoddSUqCKvzZgC8TsaULNnblbkmWYJegD6nBiwxOs7YO4KVciJSx85OiersX53F3coTeqxNUfmBcglmUQIQNbvVVZmYhyCTtCUp41m7zcE6kt+dTghBlKcYlnqG60sjG1YIGJucSweOcSMf2GVUIQWiFLSuPtrsYtIgoDmTbizP3XFiGWdERAJHyRz6gABFoxckwFGNdQKJGxnoy4fbqchdt2piW3LsSdGAeDKWiXzmnUX/ms7kjD+0mNvfQSd90B5llnQtZTh3SL85KP5sQkmvYs3jqftXeqO5M9w6+SXvfmhxWbeHkS5i9/yhBBndVYPpYTPH/W2q0Y5ydJSTuE8f1dM7I5e+JXRBgpaotwzS+mAs9t4IeE7ISsoP0vDQlhohT8SRKNH8SRRFHI7QAL46zFUr/qtLeaYJpuWy4s/oykCYlM41C0I8N5sTDZaltNj3Er/MFiiVv1l3eysliQ3IQaXp/BlGP+SFPHRVtBLAj8nHIZOEpMGBqW3X7fx7lx5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: staff
    type: Opaque
