apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: some-secret-name
  namespace: null
spec:
  encryptedData:
    EGAPRO_STAFF: AgANZCPz1t8CrjKIS5v1kDS2oL9G6JELTYHJmEcYOpha7SsL4/y0oBsuc/CVlLQzdX1sWM4mIpY8oxE5zdErQHPCaRJpOcWAhXBA6pRxOa6fwCRivZ++/WyYdjOU8L8ZheYDLUZkAgVx5Gv+za4kjLRBNX2AF48cg+abGw8zpBVY/oGQR/mIXt42Z4il9LXwNO6S3HCKNaPpZwsusl4BdHWuqtmR6gfTTV6JvQGtb85LsePQ0cxo2GOYPcMgytj5LgaYr3NtbVCUbYC5m32624musfhKwWQLTOt+yG6A56u1JYaYwwhdVVMnRCpm0z6v8+aMkj+/HXr9tvv8qu74cB0YvIMJK8EhyHqFs3ZV0OP7xDkdH3m+HoJlZq84ViSUbBGrdjHJvRkkvHMHWeftSM2mm42WxP0Q1/+Z4wRTOXYTkUJkX+j8+Z4UaSjn9dIJN/p1LQD4JWIeU86WvpqQ81jgYOdNUhAdMFPckmUFrOOjyKEloKR8cFu91UtGvYI1HpDxQ9MWO0KLW5ij1RC0DpC3gXbGv0JXE+sES4j0sz+YDtqNdHr57yamOvbeiN3Am+VdvWi6fotdFnR/ex1nCOAH2uME3BEFj2hy2lbc/iauUd5bvQUb2hwU50H0kJm63Mnji70aPUMFF55cIrs9Ih4o4ovGwAxTvyS043TG6z2hcblooDEpPs0MuDafQ7Y4dj4b+Gq58PKTcOEHOCRbR+wCE8qKxRI9Po11GERs++Q+2fDhAqmH48+GS1I/1QeMF7KuUQMmDH/cDPckMuIzahthwbJHY9oEKdlJqUJJmGSnTCSdByY7q9D7XwYBwdwXZIXoZ11QKeIHoL3Y+P+ASlxEo1Rhf3krsqgPAB+ATZOj2RH5X+HYyfXvrlXUAs/3TC6qEgg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: some-secret-name
    type: Opaque
