global:
  host: egapro.travail.gouv.fr

app:
  redirectFrom:
    - "egapro.fabrique.social.gouv.fr"
    - "index-egapro.travail.gouv.fr"
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
  resources:
    requests:
      cpu: 500m
      memory: 1G
    limits:
      cpu: 1
      memory: 2G
