global:
  host: egapro.travail.gouv.fr

app:
  redirectFrom:
    - "egapro.fabrique.social.gouv.fr"
    - "index-egapro.travail.gouv.fr"
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
  resources:
    requests:
      cpu: 500m
      memory: 1G
    limits:
      cpu: 1
      memory: 2G

valkey:
  server:
    replica:
      enabled: true
      replicas: 2
      persistence:
        size: 1Gi
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
