---

Install:
  extends: .base_yarn
  except:
    variables:
      - $PRODUCTION
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - yarn
      - node_modules
      - packages/api/node_modules
      - packages/app/node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - packages/api/node_modules
      - packages/app/node_modules

Lint:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn lint
  except:
    variables:
      - $PRODUCTION

Test:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn coverage

Build:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn build

...
