---

Install:
  extends: .base_yarn
  except:
    variables:
      - $PRODUCTION

Lint:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn lint
  except:
    variables:
      - $PRODUCTION

Test:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn coverage

Build:
  extends: .base_yarn_script
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn build

...
