---

#
.create_secret: &create_secret
  stage: "Create secret hors prod"
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  script:
    # Create egapro secrets
    - envsubst < ./.k8s/secret/secret-dev.yml > .k8s/secret/secret-dev-${PROJECT}.yml
    - kubectl apply -f .k8s/secret/secret-dev-${PROJECT}.yml -n ${K8S_NAMESPACE}
#

Create egapro/secret (dev):
  <<: *create_secret
  only:
    - branches
  except:
    - egapro-auto-devops

Create egapro/secret (master):
  <<: *create_secret
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
  only:
    - egapro-auto-devops

Create egapro/secret (preprod):
  <<: *create_secret
  only:
    - /^v.*/

...
