---

Create egapro/secret (dev):
  stage: "Create secret hors prod"
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  script:
    # Create egapro secrets
    - envsubst < ./.k8s/secret/secret-dev.yml > .k8s/secret/secret-dev-${PROJECT}.yml
    - kubectl apply -f .k8s/secret/secret-dev-${PROJECT}.yml -n ${K8S_NAMESPACE}
  except:
    variables:
      - $PRODUCTION

...
