---

#
.create_secret: &create_secret
  stage: "Create secret hors prod"
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  script:
    # Create egapro secrets
    - envsubst < ./.k8s/secret/secret-dev.yml > .k8s/secret/secret-dev-${STARTUP}.yml
    - kubectl apply -f .k8s/secret/secret-dev-${STARTUP}.yml -n ${K8S_NAMESPACE}
#

Create egapro/secret (dev):
  <<: *create_secret
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
  only:
    - branches
  except:
    - master

Create egapro/secret (master):
  <<: *create_secret
  variables:
    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
  before_script:
    - export K8S_NAMESPACE=${STARTUP}-${MASTER_NAMESPACE_ENVIRONMENT}
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
  only:
    - master

Create egapro/secret (preprod):
  <<: *create_secret
  variables:
    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
  before_script:
    - export K8S_NAMESPACE=${STARTUP}-${PREPROD_NAMESPACE_ENVIRONMENT}
  only:
    - /^v.*/

...
