---

Create egapro/secret:
  stage: Create Secret
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  environment:
    name: ${DEV_ENVIRONMENT_NAME}
  script:
    # Create egapro secrets
    - export ELASTIC_SEARCH_PASSWORD=$(kubectl get secret elastic -n ${PROJECT}-secret -o jsonpath='{.data.ELASTIC_SEARCH_PASSWORD}')
    - export ELASTIC_SEARCH_URL=$(kubectl get secret elastic -n ${PROJECT}-secret -o jsonpath='{.data.ELASTIC_SEARCH_URL}')
    - export ELASTIC_SEARCH_USER=$(kubectl get secret elastic -n ${PROJECT}-secret -o jsonpath='{.data.ELASTIC_SEARCH_USER}')
    - envsubst < ./.k8s/secret/secret-dev.yml > .k8s/secret/secret-dev-${PROJECT}.yml
    - kubectl apply -f .k8s/secret/secret-dev-${PROJECT}.yml -n ${K8S_NAMESPACE}
  except:
    variables:
      - $PRODUCTION

...
