---

Create egapro/secret:
  stage: Create Secret
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  environment:
    name: ${DEV_ENVIRONMENT_NAME}
  script:
    # Create egapro secrets
    - envsubst < ./.k8s/secret/secret-dev.yml > .k8s/secret/secret-dev-${PROJECT}.yml
    - kubectl apply -f .k8s/secret/secret-dev-${PROJECT}.yml -n ${K8S_NAMESPACE}
  except:
    variables:
      - $PRODUCTION

...
