---

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_nodejs_chart_stage.yml
    ref: master
  - project: SocialGouv/gitlab-ci-yml
    file: /base_deploy_hpa_chart_stage.yml
    ref: master


############################################
####                APP                  ###
############################################

.deploy_app_stage: &deploy_app_stage
  stage: "Deploy to hors prod K8S"
  extends: .base_deploy_hpa_chart_stage
  dependencies: []
  variables:
    REGISTRY: $CI_REGISTRY_IMAGE
    IMAGE_TAG: $CI_COMMIT_SHA
    CONTEXT: app
    PORT: ${APP_PORT}
    VALUES_FILE: ./.k8s/app.values.yml
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}
    - export APP_URL=${STARTUP}-${NAMESPACE_ENVIRONMENT}.${APP_DOMAIN_NAME}

Deploy app (dev):
  <<: *deploy_app_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  only:
    - branches
  except:
    - master

Deploy app (master):
  <<: *deploy_app_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
  only:
    - master

Deploy app (preprod):
  <<: *deploy_app_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  variables:
    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
  only:
    - /^v.*/

Deploy app (prod):
  <<: *deploy_app_stage
  only:
    - master
  environment:
    name: prod


############################################
####                API                  ###
############################################

.deploy_api_stage: &deploy_api_stage
  stage: "Deploy to hors prod K8S"
  extends: .base_deploy_hpa_chart_stage
  dependencies: []
  variables:
    REGISTRY: $CI_REGISTRY_IMAGE
    IMAGE_TAG: $CI_COMMIT_SHA
    CONTEXT: api
    PORT: ${API_PORT}
    VALUES_FILE: ./.k8s/api.values.yml
  before_script:
    - export NAMESPACE_ENVIRONMENT=${NAMESPACE_ENVIRONMENT:=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)}
    - export K8S_NAMESPACE=${STARTUP}-${NAMESPACE_ENVIRONMENT}

Deploy api (dev):
  <<: *deploy_api_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  only:
    - branches
  except:
    - master

Deploy api (master):
  <<: *deploy_api_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
  only:
    - master

Deploy api (preprod):
  <<: *deploy_api_stage
  environment:
    name: ${DEV_NAMESPACE_ENVIRONMENT}
  variables:
    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
  only:
    - /^v.*/

Deploy api (prod):
  <<: *deploy_api_stage
  only:
    - master
  environment:
    name: prod

############################################
####       DEPLOY TO HORS PROD K8S       ###
############################################
#
##
#.deploy_stage: &deploy_stage
#  stage: "Deploy to hors prod K8S"
#  variables: &deploy_stage_variables
#    IMAGE_TAG: ${CI_COMMIT_SHA}
#    LETS_ENCRYPT_ISSUER: "letsencrypt-staging"
##
#
## Dev Environment
#
#Deploy egapro/app (dev):
#  <<: *deploy_stage
#  extends: .deploy-egapro-app-k8s-dev
#  variables:
#    <<: *deploy_stage_variables
#    PORT: ${APP_PORT}
#    LIFETIME: "temporary"
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - branches
#  except:
#    - master
#
#Deploy egapro/api (dev):
#  <<: *deploy_stage
#  extends: .deploy-egapro-api-k8s-dev
#  variables:
#    <<: *deploy_stage_variables
#    PORT: ${API_PORT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - branches
#  except:
#    - master
#
#Deploy egapro/postgres (dev):
#  <<: *deploy_stage
#  extends: .deploy-egapro-postgres-k8s-dev
#  variables:
#    <<: *deploy_stage_variables
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - branches
#  except:
#    - master
#
#Deploy egapro/memcached (dev):
#  <<: *deploy_stage
#  extends: .deploy-egapro-memcached-k8s-dev
#  variables:
#    <<: *deploy_stage_variables
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - branches
#  except:
#    - master
#
#Deploy egapro/kinto (dev):
#  <<: *deploy_stage
#  extends: .deploy-egapro-kinto-k8s-dev
#  variables:
#    <<: *deploy_stage_variables
#    PORT: ${KINTO_PORT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - branches
#  except:
#    - master
#
## Master Environment
#
#Deploy egapro/app (master):
#  <<: *deploy_stage
#  extends: .deploy-egapro-app-k8s-master
#  variables:
#    <<: *deploy_stage_variables
#    PORT: ${APP_PORT}
#    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
#  only:
#    - master
#
#Deploy egapro/api (master):
#  <<: *deploy_stage
#  extends: .deploy-egapro-api-k8s-master
#  variables:
#    <<: *deploy_stage_variables
#    PORT: ${API_PORT}
#    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
#  only:
#    - master
#
#Deploy egapro/postgres (master):
#  <<: *deploy_stage
#  extends: .deploy-egapro-postgres-k8s-master
#  variables:
#    <<: *deploy_stage_variables
#    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
#  only:
#    - master
#
#Deploy egapro/memcached (master):
#  <<: *deploy_stage
#  extends: .deploy-egapro-memcached-k8s-master
#  variables:
#    <<: *deploy_stage_variables
#    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
#  only:
#    - master
#
#Deploy egapro/kinto (master):
#  <<: *deploy_stage
#  extends: .deploy-egapro-kinto-k8s-master
#  variables:
#    <<: *deploy_stage_variables
#    NAMESPACE_ENVIRONMENT: ${MASTER_NAMESPACE_ENVIRONMENT}
#    PORT: ${KINTO_PORT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /^chore\(release.*/
#  only:
#    - master
#
#
## Preprod Environment
#
#Deploy egapro/app (preprod):
#  extends: .deploy-egapro-app-k8s-preprod
#  stage: "Deploy to hors prod K8S"
#  variables:
#    PORT: ${APP_PORT}
#    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - /^v.*/
#
#Deploy egapro/api (preprod):
#  extends: .deploy-egapro-api-k8s-preprod
#  stage: "Deploy to hors prod K8S"
#  variables:
#    PORT: ${API_PORT}
#    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - /^v.*/
#
#Deploy egapro/postgres (preprod):
#  extends: .deploy-egapro-postgres-k8s-preprod
#  stage: "Deploy to hors prod K8S"
#  variables:
#    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - /^v.*/
#
#Deploy egapro/memcached (preprod):
#  extends: .deploy-egapro-memcached-k8s-preprod
#  stage: "Deploy to hors prod K8S"
#  variables:
#    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - /^v.*/
#
#Deploy egapro/kinto (preprod):
#  extends: .deploy-egapro-kinto-k8s-preprod
#  stage: "Deploy to hors prod K8S"
#  variables:
#    PORT: ${KINTO_PORT}
#    NAMESPACE_ENVIRONMENT: ${PREPROD_NAMESPACE_ENVIRONMENT}
#  environment:
#    name: ${DEV_NAMESPACE_ENVIRONMENT}
#  only:
#    - /^v.*/

...
