---

Notify Fail:
  extends: .base_notify_fail_stage
  stage: Notify Finished Deployment
  dependencies:
    - Notify Starting Deployment

Delete useless k8s namespaces:
  extends: .base_delete_useless_k8s_ns_stage

...
