---

.deploy-egapro-memcached-k8s-dev:
  image:
    name: $CI_REGISTRY/socialgouv/docker/helm:0.7.1
    entrypoint: [""]
  before_script:
  - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME
  - export K8S_NAMESPACE=egapro${HASH_BRANCH_NAME}
  - envsubst < k8s/memcached/values.yml > k8s/memcached/values-egapro.yml
  script:
  - helm init --client-only
  - helm upgrade --install memcached${HASH_BRANCH_NAME} --wait -f k8s/memcached/values-egapro.yml stable/memcached --namespace ${K8S_NAMESPACE}
  allow_failure: false

.deploy-egapro-memcached-k8s-prod:
  image:
    name: $CI_REGISTRY/socialgouv/docker/helm:0.7.1
    entrypoint: [""]
  before_script:
  - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME
  - envsubst < k8s/memcached/values.yml > k8s/memcached/values-egapro.yml
  script:
  - helm init --client-only
  - helm upgrade --install memcached${HASH_BRANCH_NAME} --wait -f k8s/memcached/values-egapro.yml stable/memcached --namespace ${NAMESPACE}
  allow_failure: false

