import { AppState } from "../globals"

export const simulationWithIndex65: { id: string; data: AppState } = {
  id: "e1b52342-0e60-11ed-a33f-0242c0a82004",
  data: {
    informations: {
      formValidated: "Valid",
      nomEntreprise: "test",
      trancheEffectifs: "50 à 250",
      anneeDeclaration: 2021,
      finPeriodeReference: "31/12/2021",
      periodeSuffisante: true,
    },
    effectif: {
      formValidated: "Valid",
      nombreSalaries: [
        {
          categorieSocioPro: 0,
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 9, nombreSalariesHommes: 9 },
            { trancheAge: 1, nombreSalariesFemmes: 9, nombreSalariesHommes: 9 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
        },
        {
          categorieSocioPro: 1,
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
        },
        {
          categorieSocioPro: 2,
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
        },
        {
          categorieSocioPro: 3,
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
        },
      ],
      nombreSalariesTotal: 36,
    },
    indicateurUn: {
      formValidated: "Valid",
      modaliteCalcul: "csp",
      modaliteCalculformValidated: "Valid",
      remunerationAnnuelle: [
        {
          categorieSocioPro: 0,
          tranchesAges: [
            {
              trancheAge: 0,
              remunerationAnnuelleBrutFemmes: 0.09,
              remunerationAnnuelleBrutHommes: 0.09,
              ecartTauxRemuneration: 0,
            },
            {
              trancheAge: 1,
              remunerationAnnuelleBrutFemmes: 0.03,
              remunerationAnnuelleBrutHommes: 0.03,
              ecartTauxRemuneration: 0,
            },
            { trancheAge: 2 },
            { trancheAge: 3 },
          ],
        },
        {
          categorieSocioPro: 1,
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
        },
        {
          categorieSocioPro: 2,
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
        },
        {
          categorieSocioPro: 3,
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
        },
      ],
      coefficientGroupFormValidated: "None",
      coefficientEffectifFormValidated: "None",
      coefficientRemuFormValidated: "None",
      coefficient: [],
      nonCalculable: false,
      motifNonCalculable: "",
      resultatFinal: 0,
      noteFinale: 40,
    },
    indicateurDeux: {
      formValidated: "None",
      presenceAugmentation: true,
      tauxAugmentation: [
        { categorieSocioPro: 0 },
        { categorieSocioPro: 1 },
        { categorieSocioPro: 2 },
        { categorieSocioPro: 3 },
      ],
      nonCalculable: false,
      mesuresCorrection: false,
      motifNonCalculable: "",
    },
    indicateurTrois: {
      formValidated: "None",
      presencePromotion: true,
      tauxPromotion: [
        { categorieSocioPro: 0 },
        { categorieSocioPro: 1 },
        { categorieSocioPro: 2 },
        { categorieSocioPro: 3 },
      ],
      nonCalculable: false,
      mesuresCorrection: false,
      motifNonCalculable: "",
    },
    indicateurDeuxTrois: {
      formValidated: "Valid",
      presenceAugmentationPromotion: true,
      nombreAugmentationPromotionFemmes: 9,
      nombreAugmentationPromotionHommes: 3,
      periodeDeclaration: "unePeriodeReference",
      nonCalculable: false,
      mesuresCorrection: false,
      motifNonCalculable: "",
      resultatFinalEcart: 33.3333,
      resultatFinalNombreSalaries: 6,
      sexeSurRepresente: "femmes",
      noteEcart: 0,
      noteNombreSalaries: 15,
      noteFinale: 15,
    },
    indicateurQuatre: {
      formValidated: "Valid",
      presenceCongeMat: true,
      nombreSalarieesPeriodeAugmentation: 8,
      nombreSalarieesAugmentees: 2,
      nonCalculable: false,
      motifNonCalculable: "",
      resultatFinal: 25,
      noteFinale: 0,
    },
    indicateurCinq: {
      formValidated: "Valid",
      nombreSalariesHommes: 6,
      nombreSalariesFemmes: 4,
      resultatFinal: 4,
      sexeSurRepresente: "hommes",
      noteFinale: 10,
    },
    informationsEntreprise: {
      formValidated: "Valid",
      nomEntreprise: "K & N BOULANGERIE ET PATISSERIE",
      siren: "825397516",
      codeNaf: "10.71C - Boulangerie et boulangerie-pâtisserie",
      region: "Nouvelle-Aquitaine",
      departement: "Charente-Maritime",
      adresse: "91 CRS DE L'EUROPE",
      codePostal: "17200",
      codePays: "",
      commune: "ROYAN",
      structure: "Entreprise",
      nomUES: "",
      entreprisesUES: [],
    },
    informationsDeclarant: {
      formValidated: "Valid",
      nom: "Macintosh",
      prenom: "Jake",
      tel: "0202020202",
      email: "admin@gmail.com",
      acceptationCGU: true,
    },
    declaration: {
      formValidated: "Valid",
      mesuresCorrection: "mmo",
      dateConsultationCSE: "",
      publicationSurSiteInternet: true,
      datePublication: "09/07/2022",
      lienPublication: "https://www.loremipsum.com",
      planRelance: false,
      modalitesPublication: "",
      dateDeclaration: "28/07/2022 16:02",
      noteIndex: 65,
      totalPoint: 65,
      totalPointCalculable: 100,
    },
  },
}

export const expectedDeclarationWithIndex65 = {
  id: "e1b52342-0e60-11ed-a33f-0242c0a82004",
  source: "simulateur",
  déclaration: {
    année_indicateurs: 2021,
    période_suffisante: true,
    fin_période_référence: "2021-12-31",
    points: 65,
    points_calculables: 100,
    mesures_correctives: "mmo",
    index: 65,
    publication: { date: "2022-07-09", url: "https://www.loremipsum.com" },
  },
  déclarant: { prénom: "Jake", nom: "Macintosh", téléphone: "0202020202", email: "admin@gmail.com" },
  entreprise: {
    raison_sociale: "K & N BOULANGERIE ET PATISSERIE",
    siren: "825397516",
    région: "75",
    département: "17",
    adresse: "91 CRS DE L'EUROPE",
    commune: "ROYAN",
    code_postal: "17200",
    code_naf: "10.71C",
    effectif: { total: 36, tranche: "50:250" },
    plan_relance: false,
  },
  indicateurs: {
    rémunérations: {
      mode: "csp",
      résultat: 0,
      note: 40, // 40 / 40
      catégories: [
        { nom: "ouv", tranches: { ":29": 0, "30:39": 0 } },
        { nom: "emp", tranches: {} },
        { nom: "tam", tranches: {} },
        { nom: "ic", tranches: {} },
      ],
    },
    congés_maternité: { résultat: 25, note: 0 }, // 0 / 15
    hautes_rémunérations: { résultat: 4, note: 10, population_favorable: "hommes" }, // 10 / 10
    augmentations_et_promotions: {
      résultat: 33.3333,
      note_en_pourcentage: 0,
      résultat_nombre_salariés: 6,
      note_nombre_salariés: 15,
      note: 15, // 15 / 35
      population_favorable: "femmes",
    },
  },
}
