import { AppState } from "../globals"

export const simulationWithIndex80: { id: string; data: AppState } = {
  id: "ea1709b4-0db7-11ed-86ff-0242c0a82004",
  data: {
    informations: {
      formValidated: "Valid",
      nomEntreprise: "test",
      trancheEffectifs: "50 à 250",
      anneeDeclaration: 2021,
      finPeriodeReference: "31/12/2021",
      periodeSuffisante: true,
    },
    effectif: {
      formValidated: "Valid",
      nombreSalaries: [
        {
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 9, nombreSalariesHommes: 9 },
            { trancheAge: 1, nombreSalariesFemmes: 9, nombreSalariesHommes: 9 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
          categorieSocioPro: 0,
        },
        {
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
          categorieSocioPro: 1,
        },
        {
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
          categorieSocioPro: 2,
        },
        {
          tranchesAges: [
            { trancheAge: 0, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 1, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 2, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
            { trancheAge: 3, nombreSalariesFemmes: 0, nombreSalariesHommes: 0 },
          ],
          categorieSocioPro: 3,
        },
      ],
      nombreSalariesTotal: 36,
    },
    indicateurUn: {
      formValidated: "Valid",
      modaliteCalcul: "csp",
      modaliteCalculformValidated: "Valid",
      remunerationAnnuelle: [
        {
          tranchesAges: [
            {
              trancheAge: 0,
              ecartTauxRemuneration: 0,
              remunerationAnnuelleBrutFemmes: 0.09,
              remunerationAnnuelleBrutHommes: 0.09,
            },
            {
              trancheAge: 1,
              ecartTauxRemuneration: 0,
              remunerationAnnuelleBrutFemmes: 0.03,
              remunerationAnnuelleBrutHommes: 0.03,
            },
            { trancheAge: 2 },
            { trancheAge: 3 },
          ],
          categorieSocioPro: 0,
        },
        {
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
          categorieSocioPro: 1,
        },
        {
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
          categorieSocioPro: 2,
        },
        {
          tranchesAges: [{ trancheAge: 0 }, { trancheAge: 1 }, { trancheAge: 2 }, { trancheAge: 3 }],
          categorieSocioPro: 3,
        },
      ],
      coefficientGroupFormValidated: "None",
      coefficientEffectifFormValidated: "None",
      coefficientRemuFormValidated: "None",
      coefficient: [],
      noteFinale: 40,
      nonCalculable: false,
      resultatFinal: 0,
      motifNonCalculable: "",
    },
    indicateurDeux: {
      formValidated: "Invalid",
      presenceAugmentation: true,
      tauxAugmentation: [
        { categorieSocioPro: 0, ecartTauxAugmentation: 0.02, tauxAugmentationFemmes: 0, tauxAugmentationHommes: 0.02 },
        { categorieSocioPro: 1 },
        { categorieSocioPro: 2 },
        { categorieSocioPro: 3 },
      ],
      noteFinale: 20,
      nonCalculable: false,
      resultatFinal: 2,
      mesuresCorrection: false,
      sexeSurRepresente: "hommes",
      motifNonCalculable: "",
    },
    indicateurTrois: {
      formValidated: "Invalid",
      presencePromotion: true,
      tauxPromotion: [
        { categorieSocioPro: 0, ecartTauxPromotion: 0, tauxPromotionFemmes: 0.02, tauxPromotionHommes: 0.02 },
        { categorieSocioPro: 1 },
        { categorieSocioPro: 2 },
        { categorieSocioPro: 3 },
      ],
      noteFinale: 15,
      nonCalculable: false,
      resultatFinal: 0,
      mesuresCorrection: false,
      motifNonCalculable: "",
    },
    indicateurDeuxTrois: {
      formValidated: "Valid",
      presenceAugmentationPromotion: true,
      nombreAugmentationPromotionFemmes: 0,
      nombreAugmentationPromotionHommes: 3,
      periodeDeclaration: "unePeriodeReference",
      noteEcart: 0,
      noteFinale: 25,
      nonCalculable: false,
      mesuresCorrection: false,
      sexeSurRepresente: "hommes",
      motifNonCalculable: "",
      noteNombreSalaries: 25,
      resultatFinalEcart: 16.6667,
      resultatFinalNombreSalaries: 3,
    },
    indicateurQuatre: {
      formValidated: "Valid",
      presenceCongeMat: true,
      nombreSalarieesPeriodeAugmentation: 6,
      nombreSalarieesAugmentees: 6,
      noteFinale: 15,
      nonCalculable: false,
      resultatFinal: 100,
      motifNonCalculable: "",
    },
    indicateurCinq: {
      formValidated: "Valid",
      nombreSalariesHommes: 10,
      nombreSalariesFemmes: 0,
      noteFinale: 0,
      resultatFinal: 0,
      sexeSurRepresente: "hommes",
    },
    informationsEntreprise: {
      formValidated: "Valid",
      nomEntreprise: "K & N BOULANGERIE ET PATISSERIE",
      siren: "825397516",
      codeNaf: "10.71C - Boulangerie et boulangerie-pâtisserie",
      region: "Nouvelle-Aquitaine",
      departement: "Charente-Maritime",
      adresse: "91 CRS DE L'EUROPE",
      codePostal: "17200",
      codePays: "",
      commune: "ROYAN",
      structure: "Entreprise",
      nomUES: "",
      entreprisesUES: [],
    },
    informationsDeclarant: {
      formValidated: "Valid",
      nom: "Mauguet",
      prenom: "Pierre-Olivier",
      tel: "0688125052",
      email: "acte@tours.fr",
      acceptationCGU: true,
    },
    declaration: {
      formValidated: "Valid",
      mesuresCorrection: "mmo",
      dateConsultationCSE: "",
      publicationSurSiteInternet: true,
      datePublication: "27/07/2022",
      lienPublication: "12",
      planRelance: false,
      modalitesPublication: "",
      dateDeclaration: "29/07/2022 14:41",
      noteIndex: 80,
      totalPoint: 80,
      totalPointCalculable: 100,
    },
  },
}

export const expectedDeclarationWithIndex80 = {
  id: "ea1709b4-0db7-11ed-86ff-0242c0a82004",
  source: "simulateur",
  déclaration: {
    année_indicateurs: 2021,
    période_suffisante: true,
    fin_période_référence: "2021-12-31",
    points: 80,
    points_calculables: 100,
    index: 80,
    publication: {
      url: "12",
      date: "2022-07-27",
    },
  },
  déclarant: { prénom: "Pierre-Olivier", nom: "Mauguet", téléphone: "0688125052", email: "acte@tours.fr" },
  entreprise: {
    raison_sociale: "K & N BOULANGERIE ET PATISSERIE",
    siren: "825397516",
    région: "75",
    département: "17",
    adresse: "91 CRS DE L'EUROPE",
    commune: "ROYAN",
    code_postal: "17200",
    code_naf: "10.71C",
    effectif: { total: 36, tranche: "50:250" },
    plan_relance: false,
  },
  indicateurs: {
    rémunérations: {
      mode: "csp",
      résultat: 0,
      note: 40,
      catégories: [
        { nom: "ouv", tranches: { ":29": 0, "30:39": 0 } },
        { nom: "emp", tranches: {} },
        { nom: "tam", tranches: {} },
        { nom: "ic", tranches: {} },
      ],
    },
    congés_maternité: { résultat: 100, note: 15 },
    hautes_rémunérations: { résultat: 0, note: 0, population_favorable: "hommes" },
    augmentations_et_promotions: {
      résultat: 16.6667,
      note_en_pourcentage: 0,
      résultat_nombre_salariés: 3,
      note_nombre_salariés: 25,
      note: 25,
      population_favorable: "hommes",
    },
  },
}
