apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: audit-cleanup
spec:
  encryptedData:
    EGAPRO_AUDIT_CLEANUP_TOKEN: AgCObch5y/lfmKrFdJiYy8LHpN2eDbb4cNPoh8OAJxrzHkPECvKO7bO12eiGllB4HOw75NBnvhiyhZwHhLpJjUVLSnrBBaS6L5bIo6Ei4Q3m+UPaPp4zNGZsaqvpCvWxGKWehPxVKox8ZL/E3JyHLnkSTDY2X3b0nGtQVvJz43tokrmno7LjNBXl4/R07+MCwYzoR4cDu8RiCVr9XIy/A2dxv57IpGYJgGDwXGv9re6H/RPOByV+TMoYuBV71O8TrPEYloiyTGvNtkBxY7o4gFv9oeC+BleJ3HM4y2vx+8JPeC6u7iaeIKEN4cHhwLzx87cMzVXqV/VFCrhXULk5+UKoakW2mQIfDIrhLs6wgJFiaNsmFU6gUjjLpHLqMZ3+kCB4N7ZSLF7qCzNgjhenAeJ55b25b+7Xs6er5Rv35G5EfwMEFe9kXdPHUFvuVxi71kYABxLUx1vMP7w3QDQrbjr/8PhDk0Wfzd7EJVw5H+nhyoInQScYqi0xkATUdw66ibW9yQGYh20nSZCrOziZ38CZiFI2/Cuyw91ILjxHXhQJ8FDvFcAnR9xtNBQ211rx69k9ghC9Rj5ZPiUOwphZUTKBH/4HfUKMCoPPlcFSKtVqxbMg3/duB6JlTULiM+mzxSZEekulI4eBdjveAYHIdYTuQSctYsT3jfn9q/LEX1in8hyXJwpctmH6oyuFfT17NIlBhOtDBo85pfhJON1BzwutElsFumBIXdyPm/MYffkvYZNLQ1yzUXV8BriRdKIkA7bPecByG3poRMQcMn0kadyo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: audit-cleanup
    type: Opaque
