apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: export-api
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgCfHjfg/RAQskbQBLroKA+R53Lr0X9zFBZiMslyOEPwxS2Yrrjh8/XPgyMsrWf5aFjvORzZQN3Q9Kx6HZaxv21g4DSAZD1pABw7LjThlY6B/xGm4pWZWxTWaQEgiZRzAYO0tsCifh25VYb8mAnZ5ucFVFlMMxczvpHBcnKJJRtul6o6DppGi99Et+q+FKffbMcHpjwY0yJF49ieECUmhsNtbdf7zGJtoeLvKe8czYedR9cy0W2sF9Ti2jY3fxA3mjwAs/rJI2N1qceTpjqQDZ5S05b34lNn2Fgvv7M0+Y2EclBEMpJp+5GNtcdM/7/9CidPAQnBTcLIMjy2J1EljsAhSCpgTT5TD2RYJzC/Rr6Cv4Z7WvJPdY5laMqn1YR2HIgEUm04yM27K13YT0SHqncv9tp8uxfuQa+I9wEOul+2YsCOBaIUT+KNQFYJ75+3Lw5cIujRdMC7W4nhIVV396PIt6Ja6MzkNYmG3JvkGltBbHxTUal0kevSCy0CUSMUENUusSZy5tPb1DkWoNPTWaoV0ntI9BattP7Sf9rwzEYnFELKKUCWD7p+Lc0q2O8vnvTnv5t7CR38wc20dYb7LJgEy8FmRLavkcapHAoVPsdvXplIcVIWhc2e45iQkE50WkjpStBRw3r7/2Tct48engD5jpxQwjvxvN2i1Lc9nQoCPlk5Sd2sQjtu9xubzuwEHUOccoW6L3kPHLdCyFPdIkELM/Vj2xJ/bxa4XbVaJrbxruCg75B06JeHnffynK4BLQI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: export-api
    type: Opaque
