apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: export-api
spec:
  encryptedData:
    EGAPRO_EXPORT_API_TOKEN: AgBogtAzs6AvigxGNpwXNA/ghG6qrmjCXa0QxLZYFBFfL7upZyzmyCqgWx+gaLMDS67HHc2gJA3lywdHOAOUrBx03PFyUhkf/Povlu6DdcTHxL07OI5IsNbiVE041VqbdLXyTtLk3LHgwbFMH2ufCC+XawkCgxR1dh/Pe7929WBzhNCBXpWOf9zKVS1Hsz8CiGqDbj7OhCKSccywsEPnWhHUpDILTNWKYsPkGMmG/HKtAttRPLz/PLPYXfkBTa4dpnIdLL+/Zygi8ps8xS4Y6tYXA3EyDGegbGoIyqRm45g1Xgsa2n/TbsyPjq5SZGdxBXjmmLZkGIwCSV2ZPekjQgsRRPXQo0RJWwMRhFOK4ojJ2+W0wUJ0IAO+Cpl1NZWpFE7S+5Rp+R1GOV3QPZI1D4+htxmY9zS+wOcRKe2//iUvAG2U1AOtwzmdJ3LVM5MBUul9vqnjmeuoIn+Hux3WvAGlJfYUSOuGKbi6j8AAg9WQtgcncljm6jJsYTWu0iDG5BJfFdPUyrGiw3AXWpvDGgaIPPD/YM0/RzmBhRRJK48YFMLNMSiOEm+bdiuiuIy4cR+huUNlnyRp7k8g4dD4fxkdF+KNBLed5j2H0fLN3cRATcbDMjJvvl1i7DUbgPaVI89l71cJ3ST700+kfCwzVUrkyfnMwHue1Ee4QHU9f6YRdaeNoKQQrYL34KtCm+vQHTWV1NEiMFGgi0kzGLmX8QyxgdApqxj3Kg7QErTdJy3z+qaUocKtiPuD2UZVKpGe1q0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: export-api
    type: Opaque
