apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gip-mds-import
spec:
  encryptedData:
    EGAPRO_GIP_MDS_API_TOKEN: AgBgw/oj6xguWU4IHcq9/muNjvbhsJw5wJZ61ZMpVptB4d/zgkDf3QAw6OwNBNrmQ0zZNzmIW+2j8MscHy5paZqwboWi0vb0MaOQfHxTUsk0OzlVLcL0PrKJaxTjkduL65uh5uCdMCJcV68P5sl8Gl66eedfSz6KiRzfvpaqctLdMy4IYqB4tFVwkEiesnp+9UdxNP0W7laopQYJxavGTboSWP6Dfll0dGiX/uHJFl7puPYvYp2jZN81YTOk7FGmg77YemdX8YezVyl88hJqLaiutJ56OFHehkZH8jwR8Cgk2n05sHf83kdkiAJ/eprMg5Nbcbh8eqg55HTt1NaOClhlDWxZPi21vdKFpXVGZxQYeVMZbHYVvhoNczqXxYskKeAr2lrULuQZD52135kaSjQxHMzNSQ8z/Naau42MQzjxcSWKcZj0Zr285/V6mm0tv/IxFTC5CfKTsZfw6XQpFqTxS32DxCJWnGTKBcGH9fCWmkXezbBybRRQ5Qs43nam4hT/UgAfXiwtvX5rMYDoweYpiGWLYRXNE/q1eK0HqxPPlgVzqZ8d+15O2O7XZaKKuXsSHzmD6C0O2ecMOJgBaD4iVwPlMLY/aFbH4r5LLmLNd9t+eTaQ60k7P5k32vz8wcc+pETvgj+uxuZfgOdOPgTVvA6oliuB15V/uHxVnG5PdoKaJpWMtkXeTmbTp1lSPhBEDO4WO0377E0ryig8QnLkVJ4SYkD7mxUNTspLwMIoVj0/OYx/eC3+wpu/sQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gip-mds-import
    type: Opaque
