apiVersion: v1
kind: Secret
metadata:
  name: moncomptepro
type: Opaque
stringData:
  SECURITY_MONCOMPTEPRO_CLIENT_ID: "egapro-local"
  SECURITY_MONCOMPTEPRO_CLIENT_SECRET: "egapro-local-secret"
  SECURITY_MONCOMPTEPRO_TEST: "true"
