apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: next-auth
spec:
  encryptedData:
    AUTH_SECRET: AgADR4c7z92r3OXxKzS4Fryfc2kIFESR7/ed224vhV845lgKmxzkCYyDQbccUgK0N2P5wVPAt/DGmOFMtEwA7dcGI093K50rKqMTDN5KubY8NaQBTburF5AxpnPFZHy23vcsTDoMZb/aUMfhnOeZn0F1pWL2g+nmcx9KHDQ+Xh+rpv0vGnDvUY9WrWGxg1N1VCe8zq6wF8I7t54Mu1kmh1Dp8U+MPbnn/YSOCuLJ8kVFa3gdgffMQ8LaBR+A9m3vxK2Q3MoWje0NXWwCruloANosEDgTkmc62IpvaB7zP2Mdasu6lri6xYu7ZbnanO6I78MsuctdMZ6A9HpHVwJ0jT4H+RCLdM8Ph41BYok5z+Yh9Ld/17vyfjrW83Ihoh7VMu9x/nlvDZ7u7wXFWeAolyF95MD6gGqgkEk20StwV05d11ltNoJKlkWX8jZ54sJpuT4z5lfJlLrSBG6RYop90PMxY4Cp6EoDA6fPYz5hpUwFSXXlgbiBI7vWELDyUTPOWbzrTaX1cCxu31Owxnno5/HT/wqWXW86RIFNh19Xm6/oSQE4lJUhnPzQID6x8thZg6zDFGxnAsAag5cSL7ewkTZ4vl1jI7Vgoqx2BBJ2dmo/3shTxbwBPpODx6yQz31szeHybsroSQQDKaUcdAvMJ/Q2GCMhbSsQ1gd2CNMqeCRnvW5hmjlUuZDnw08uf0NtgHtyEDprJaMjCRiGbXfEuZPsUVw8fvmAfcj9rc1dqxkfXnOtZGDzAa6DlXbJ7Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: next-auth
    type: Opaque