apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: proconnect
spec:
  encryptedData:
    SECURITY_PROCONNECT_CLIENT_ID: AgC0+8flTsyNFQW38lYj200NcAVCIMy8R6FQf4tShoaYyqREvZT4YfsSHcJy1tJwjICe+yzj0eJuvuXLgzLVPoBpL4l/3KVlm31gJ74bLeJ8K2SdfAlUSehK6iQVroS+ORzRnJ5iXWeNNdYQnqmYub9zR475LFcd24tkWtipMdngh54mblk3ld8ses0taQ+UosL3PDlnBqOBMAm30DWgiYdi0n0Dg5ipahQwE1/cr6jLVOvhuTTWx+to8ZqHATV21MslBy/iaf4Pdaw5vbuZGH0M7FVUKchOZg3AsVyI6gT+5jjiSz0QP6Uzdffk0f58tCQW8NedAJ11zsg9N+P/G7jLe7Qk/Y8He8COEqwFPcs3Ul0sVrA3PGv+wWnefxHXvHe5B1lJ8863AV5++qFt07bWF657sVE+tizIv9fanMSgW8JenZ49/otSFLgfi/b1udBZNn4KCWW92MaeQSOLNmeDFO6T5FsarCujK1rp5ex1Vl4F/mh5zD8jL7awBRHaGV90sAF26WwlNchYtMnCrGQt9/p3cLtW42KkiW4Vp1JJEQ0JRc1T0o3jC3tzL64OYPYaRv8W7RHNa8w4Bg+fCz6Kfta6xhKs64a6SZTtm5AZK9HM228JZrPsvhle8JDPsgZ/TY2jsNqrOx+y5bqP0iGnKekbHgViaxwT1b9cVZVQqjChn6jr5f5ENE1febNWfWvVqdp7MG+2FrgOKKyTYQCBPdH3B0HoZknmiWbQ6GuH4ljeU/PBh2jpKv5fpst2Cesk3UwvmY1pfSycsn7r7Z7M
    SECURITY_PROCONNECT_CLIENT_SECRET: AgCX4bvjfIjdZrAUxyJA605hxGQeZv0Chl2lOPLN6ZmE3gkE755ICsA0WCE8JURE3xEI/UdF06/w1Vr3Llfai0D9pEdZSmahIcTtpydyyTXSIz5iZYvQl3h2KtFjA/n/pTHvcRX3ph7Pfhun8OQj7Cm2tEgTjMmq+7mOK7zF7/Wt/5CEnSY/32Ub2sS4KbFDSFUWrYHscK6VuEl1Azi1nJ44qsDGVqig4AwvDqk3JYNu5zbcDkJng4wINAu/WCnmv+RCLS2HFzesAJ+3pug/FGJf18voLpqUu+kzV0jMDqimEL5bRqXtx6amdGluidq9Ilr6tru0GtUqv3OLMaKVVKieY+aFxETb47I+6/0viAtuf16872GwOkA9LOSoUA53HbUWCt5exFr9u5+qVyqZB3qWd5pAcApHRFtUQJYHZksHCHx9kAp/LVLmVNabCGPCeqxnOwirdvhybDhUuhUPnoZCyFDDdM4sS04KdWQo/A6yJq3pM5lCASxnutkwRVfa937fFEQUlXnx9mbklvU5BOhXVV0JLNKTAlPyEyuWo3ehfBQaLXmTtc4CXABk+Im4GzhzM6qKE+ksOQp36Ck0lmc30nRQX+UNM98x08KblZvtyt9pfW6jY5bNthhNeqfnl44UD/57hcmr/5Qv5kqPqPDtzt3rwM8hkWf8cDNczzw84tKCO7TqOausTGpc7N132YR4Ou+/YvsH2A34ag7sQOvRq4lTUgdl5aRWtejsgq+FlwUAVciFApbIBZvINyAbrcqiC9TTDm3okacMiag83ANi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: proconnect
    type: Opaque
