apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: s3
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCvuM12JZFMjJ8KTDIz3IXXeWj99izf3AJDRE7lJZlYQf0QjpgTbggrpxecnf4R7LWfFDWKj3FZXCJuimYXd0D2YvE7Aylpxj/pLC/AlfUX0UGyvBLoOduR8Wy7wExulu4yTmepApcLktFYKySV9YGG+kxPpIqvtK1BJXZWuJ2gNwwvkGXJufrH/BB3cdtYxaEyx4hrYK0TyN88y6xnl95tX63LHv/0aUI3rFYukn44BOjtBVdYEKNWF8le9wcIFYcvrYqvEeKQ/V5GI8WvByhhwcCiVo8uuG4+S//34L5KXKdocsT1dqStkog6EL+URBhys1PqUIvjexjC1YOPMVrSUrRZ0+lYHt3o0bZ1HTtG3gb/sGrVnaM1XdEHkEVNLtvirYTur/KVcjRlJ2pWMFZP18h0Trd0a8RJOvzlgxIKMpMTg8lgdUfFixqQUMl8dWywWT8PIsDdeZyYamHdm1Bh5svU9/qvfcZBzxtivZ4xErcTG09f0EafupocI0mkzhonPLaoDCWsrVsihubVo5z/6KSxRqDd/1xEv8+I+y+3rrPVn8yPZWxFjjfl8TkSx5kp4FlgwpwTK3YhFtBl8JEv5c0D/1yB6SsyPXa2/6olIe8keQI1sH21NeBxJ5WcnMaq95lSz43c9Q4ZY4oj9nAkYuvFprPDF79Lrei1r9UJ6KCBBYwWQmJecLhzx2522AiQf+S6IorprNPJ3OzI6pHrLs6OX50pwh/oVO6IGKK1JA==
    S3_SECRET_ACCESS_KEY: AgCmuD8F6sQ3AJJO4L4RybxBULCIst9LJLhK4C1AvOOoqkG+Ub5rkLJncQXpMpJKjJx/pLmHLfCQyVRVBamMbzZ5ll7KxukMacXHvdP5VxQXsAiM6AH61DyYk0PEXqPvG2YsMLPz4o7y6qs0dTZ7AcBwgX0k1t/uruI+BWenmihv09xH/EEUwZNAG6mmpc6Xw93sXiNOiWMxidBdUyWKTK3yJq6zzDWytVejHTwPztjwx4+GQDs11U5SnXKqnuxEkVDTyHMmwgckdKNkNVGIRf5hborklqYipEznt+2SiQiIwczrEeF/U+ybRx7BvWXjmWUkLfZul12cvgRW/5JwRe8RfYs7KT6sVoGue/Us65WtfGsbjPPMK63QA3gIO4UTX5jDpSL0GkwoQs+fDTcTJIIJMcOAeMUV0fsPyjVvl/ug7BCz8NZncsO6DWeO8GOXtrfrnvNkmDIWk3GXKPapXEzf0ptnmXu0PSf/fow266i6oaQN+R0Z9z/RtiDIY2ztNkbSNHk1xHnKWdznWSMNrNgNsrSSteQSUifvbbaZvI3I57SuD734RfEb3/rs6IWC6PKF8oL2kTlw6284CvKX2Qpu7PWZ7m+LxI5O9s1TQ9czsUR9mQE05HYIDmNlC8beD9AkvYRwpaALyXQ1k35L9wLR9MjxBm/YmQ6SENegtEezU4vrdo2OB4IgxmKCoMbdyJMVRq59UdBCdLjSR9Udogbd0ZMDT14f7b7pQXyTOzmHzw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: s3
    type: Opaque