apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: suit
spec:
  encryptedData:
    EGAPRO_SUIT_API_KEY: AgBMsYKmYyq9U2QWomidPT2EiXkQqvPqRBhXmmfy8CauTudFjxdeKLyau2c2FiRDoICpFQzJUg259GbeGOik5lbKFJfAba/xCVIwZAYdMrkouRnxZXRwUAAhOFyoJm/ferXVVBhitfq0sbfKJt1nvy577mWZHwp4eX1jk/FUwhduC2xist8xTm01gcwBTSYxrdT+Eao1gfgAECPlYhZkX7oPTajbEyLb9zUZNszVY6jcPQkOZfVnIWwaOq+rDAYMa00qxoemyN91SVcIvMffwJaxeZA+lpIM+XRKf4cKjZyG5XVhn6/CBfXpkwuNlHLvEODXKqc1drlijuVAOFVwMeZoZk01CQdPS5nKIOx2a2wHxqYzGEPLLK/4oYXUB6ZMwRhv+v6wLxDTslazM4yKKoNfJ8lJLz+jDnLUYDojijUioJYk5ioDfXru+QWQ07r5yQ5GcbUeIHT3KdiVdSSiQ3wNet/L0Jf6siKJQaw3HnioG1xMs75qtBUyQPzMfrhqvKAAC8wo3a82aQ6/Gl65TVbnORjzLB6lffKFutfZh3wqZQfTMX7lYgP00BQQ6WWhkYB3LptIb/+BW92UCEBk7DVC/gJ2BDXYiyolk0IFiOPwQ7IuArxNSQoEC23KHy9AIcW7Lm6LnqYWbc0QOtRFCH1vVJaZBumNv6Jm3SzZ+z3hUeNm+f9BfLVC5kldwGTX++r3EtYpVc78B1AJga/5aIGpe8F7vHX/IZ8G1PAjFS218ZkeSDoIz6rP3n1DHk9n/5iAU5QluOz+oYHWwWJhTlhW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: suit
    type: Opaque