#!/usr/bin/env bash

set -e

rm -rf node_modules
rm -rf packages/app/node_modules packages/app/build
rm -rf packages/api/venv packages/api/egapro.egg-info
rm -rf packages/simulateur/node_modules
rm -rf packages/simulateur/build

yarn