#!/usr/bin/env bash

set -e

if [ "$PRODUCTION" = "" ]; then
  ## DEV ONLY
  
  if [ -n .env ]; then
    cp .env.sample .env
  fi

  ROOT_DIR=$PWD

  # install python package on local laptop (used for running tests from laptop)
  cd packages/api
  if [ ! -d venv ]; then
    python3 -m venv venv
    set -o allexport
    source venv/bin/activate
    ./venv/bin/pip3 install -e .[dev,test,prod]
  fi
  cd $ROOT_DIR

fi