#!/usr/bin/env bash
#
# Bootstraps an isolated dev environment for a single worktree:
#   1. Computes unique ports from the worktree index (multiple worktrees side-by-side)
#   2. Writes packages/app/.env.local with ports + service URLs
#   3. Starts the docker-compose stack with a worktree-specific COMPOSE_PROJECT_NAME
#   4. Runs migrations against the fresh DB
#
# Usage:  scripts/setup-worktree.sh <index> [<extra-service> ...]
#
#   <index>          worktree index assigned by /epic (0, 1, 2 ...). Drives all port
#                    offsets; must be unique among concurrent worktrees.
#   <extra-service>  optional service names to start on top of the default stack
#                    (currently only `clamavd`). See `docker-compose.yml`.
#
# Defaults started: db, minio, minio-init, maildev, valkey.
# ClamAV is heavy (~1GB RAM) — opt-in per ticket.
#
# Must be run from the root of a worktree (containing docker-compose.yml).

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <index> [<extra-service> ...]" >&2
  exit 1
fi

N="$1"
shift
EXTRA_SERVICES=("$@")

if ! [[ "$N" =~ ^[0-9]+$ ]]; then
  echo "Error: index must be a non-negative integer (got: $N)" >&2
  exit 1
fi

if [ ! -f docker-compose.yml ]; then
  echo "Error: docker-compose.yml not found. Run from the worktree root." >&2
  exit 1
fi

# Branch-based project name → unique containers/volumes/networks per worktree.
# In detached-HEAD mode (how /epic provisions worktrees), `git branch
# --show-current` returns empty; fall back to the worktree directory name,
# which encodes the ticket (e.g. egapro-epic42-t123).
BRANCH=$(git branch --show-current)
if [ -z "$BRANCH" ]; then
  BRANCH=$(basename "$(pwd)")
fi
SLUG=$(echo "$BRANCH" | tr '/' '-' | tr -cd 'a-zA-Z0-9-' | head -c 40)
COMPOSE_PROJECT_NAME="egapro-wt-${SLUG}"

# Port allocation: base + 10 * index, stepped enough to avoid overlap.
APP_DEV_PORT=$((3001 + N))
POSTGRES_HOST_PORT=$((5500 + 10 * N))
MINIO_API_PORT=$((9100 + 10 * N))
MINIO_CONSOLE_PORT=$((9101 + 10 * N))
MAILDEV_SMTP_PORT=$((1100 + 10 * N))
MAILDEV_WEB_PORT=$((1200 + 10 * N))
CLAMAV_HOST_PORT=$((3400 + 10 * N))
VALKEY_HOST_PORT=$((6400 + 10 * N))

ENV_FILE="packages/app/.env.local"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-worktree.sh (worktree index $N)
# Branch: $BRANCH
# Regenerate by running the script again; teardown with scripts/teardown-worktree.sh

COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME

# Host ports (docker-compose.yml reads these via \${VAR:-default} expansion)
POSTGRES_HOST_PORT=$POSTGRES_HOST_PORT
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
MAILDEV_SMTP_PORT=$MAILDEV_SMTP_PORT
MAILDEV_WEB_PORT=$MAILDEV_WEB_PORT
CLAMAV_HOST_PORT=$CLAMAV_HOST_PORT
VALKEY_HOST_PORT=$VALKEY_HOST_PORT

# App runtime
PORT=$APP_DEV_PORT
DATABASE_URL=postgresql://postgres:postgres@localhost:$POSTGRES_HOST_PORT/egapro
CLAMAV_PORT=$CLAMAV_HOST_PORT
EOF

echo "[setup-worktree] Wrote $ENV_FILE"
echo "                 project=$COMPOSE_PROJECT_NAME"
echo "                 app=http://localhost:$APP_DEV_PORT"
echo "                 postgres=localhost:$POSTGRES_HOST_PORT"
echo "                 minio=http://localhost:$MINIO_API_PORT (console: $MINIO_CONSOLE_PORT)"
echo "                 maildev=http://localhost:$MAILDEV_WEB_PORT"
echo "                 valkey=localhost:$VALKEY_HOST_PORT"

# Core services always needed.
SERVICES="db minio minio-init maildev valkey"

# Optional extras.
for svc in "${EXTRA_SERVICES[@]:-}"; do
  [ -n "$svc" ] && SERVICES="$SERVICES $svc"
done

echo "[setup-worktree] Starting services: $SERVICES"
docker compose --env-file "$ENV_FILE" up -d $SERVICES

# Wait for Postgres health.
# We check both internal (via docker exec) AND host-port reachability — on cold
# start, pg_isready inside the container can return ready before Docker has
# fully wired up the host port forwarding, causing drizzle-kit to fail with a
# silent ECONNREFUSED hidden by its progress spinner.
echo "[setup-worktree] Waiting for Postgres (port $POSTGRES_HOST_PORT)..."
for _ in $(seq 1 60); do
  if docker compose --env-file "$ENV_FILE" exec -T db pg_isready -U postgres >/dev/null 2>&1 \
     && PGPASSWORD=postgres psql -h localhost -p "$POSTGRES_HOST_PORT" -U postgres -d egapro -c 'SELECT 1' >/dev/null 2>&1; then
    echo "[setup-worktree] Postgres ready."
    break
  fi
  sleep 1
done

# Install workspace dependencies if missing. pnpm hardlinks from the shared
# global store (~/.local/share/pnpm/store), so cold-cache cost is the only
# slow run; subsequent worktrees are ~10-15s.
if [ ! -d node_modules ] || [ ! -d packages/app/node_modules ]; then
  echo "[setup-worktree] Installing dependencies (pnpm install --frozen-lockfile)..."
  pnpm install --frozen-lockfile
fi

# Run Drizzle migrations against this worktree's DB.
# drizzle-kit reads process.env directly and does not load .env.local
# (unlike Next.js), so source the file into the subshell before running.
# Retry up to 3 times: drizzle-kit's progress spinner hides errors, and
# transient connect failures can occur on cold-start before Postgres is fully
# accepting host-port queries even though pg_isready returned ready.
echo "[setup-worktree] Applying migrations..."
MIGRATE_OK=0
for ATTEMPT in 1 2 3; do
  if (cd packages/app && set -a && . ./.env.local && set +a && pnpm db:migrate); then
    MIGRATE_OK=1
    break
  fi
  echo "[setup-worktree] Migration attempt $ATTEMPT failed, retrying in 3s..." >&2
  sleep 3
done
if [ "$MIGRATE_OK" -ne 1 ]; then
  echo "[setup-worktree] Migrations failed after 3 attempts." >&2
  exit 1
fi

echo ""
echo "[setup-worktree] Done. Worktree $N ready."
echo "                 Teardown: scripts/teardown-worktree.sh"
