---

#
.deploy_egapro_memcached: &deploy_egapro_memcached
  image: $CI_REGISTRY/socialgouv/docker/helm:0.7.1
  script:
    - export K8S_NAMESPACE=egapro${SUFFIX_BRANCH_NAME}
    - helm init --client-only
    - helm upgrade --install egapro${SUFFIX_BRANCH_NAME}-memcached --wait -f .k8s/memcached/values.yml stable/memcached --namespace ${K8S_NAMESPACE}
  allow_failure: false
#

.deploy-egapro-memcached-k8s-dev:
  <<: *deploy_egapro_memcached
  before_script:
  - SUFFIX_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export SUFFIX_BRANCH_NAME=-$SUFFIX_BRANCH_NAME

.deploy-egapro-memcached-k8s-master:
  <<: *deploy_egapro_memcached
  before_script:
    - export SUFFIX_BRANCH_NAME=-master

.deploy-egapro-memcached-k8s-preprod:
  <<: *deploy_egapro_memcached
  before_script:
    - export SUFFIX_BRANCH_NAME=-preprod

...
