import type { PublicDeclarationDTO } from "~/modules/public-api";

/** A complete declaration, so a test only states the fields it cares about. */
export function declarationFixture(
	overrides: Partial<PublicDeclarationDTO> = {},
): PublicDeclarationDTO {
	return {
		year: 2027,
		siren: "998900001",
		name: "Alpha Solutions",
		address: "12 rue des Innovateurs, 75011 Paris, France",
		city: "Paris",
		regionCode: "11",
		region: "Île-de-France",
		departmentCode: "75",
		departmentLabel: "Paris",
		countryCode: null,
		countryLabel: null,
		nafCode: "62.02A",
		nafLabel: "Conseil en systèmes et logiciels informatiques",
		workforceEma: 2256,
		totalWomen: 752,
		totalMen: 1504,
		hourlyWomen: 700,
		hourlyMen: 1400,
		globalAnnualMeanGap: 0.005,
		globalAnnualMedianGap: 0.0271,
		globalHourlyMeanGap: 0.0717,
		globalHourlyMedianGap: 0.0772,
		variableAnnualMeanGap: 0.1,
		variableAnnualMedianGap: 0.12,
		variableHourlyMeanGap: 0.207,
		variableHourlyMedianGap: 0.3127,
		variableProportionWomen: 0.571,
		variableProportionMen: 0.667,
		annualQuartile1ProportionWomen: 0.667,
		annualQuartile2ProportionWomen: 0.571,
		annualQuartile3ProportionWomen: 0.436,
		annualQuartile4ProportionWomen: 0.366,
		annualQuartile1ProportionMen: 0.333,
		annualQuartile2ProportionMen: 0.429,
		annualQuartile3ProportionMen: 0.564,
		annualQuartile4ProportionMen: 0.634,
		hourlyQuartile1ProportionWomen: 0.465,
		hourlyQuartile2ProportionWomen: 0.471,
		hourlyQuartile3ProportionWomen: 0.455,
		hourlyQuartile4ProportionWomen: 0.308,
		hourlyQuartile1ProportionMen: 0.535,
		hourlyQuartile2ProportionMen: 0.529,
		hourlyQuartile3ProportionMen: 0.545,
		hourlyQuartile4ProportionMen: 0.692,
		...overrides,
	};
}
