import type { PublicDeclarationDTO } from "~/modules/public-api";

/** A complete declaration, so a test only states the fields it cares about. */
export function declarationFixture(
	overrides: Partial<PublicDeclarationDTO> = {},
): PublicDeclarationDTO {
	return {
		year: 2027,
		siren: "998900001",
		name: "Alpha Solutions",
		address: "12 rue des Innovateurs, 75011 Paris, France",
		city: "Paris",
		regionCode: "11",
		region: "Île-de-France",
		departmentCode: "75",
		departmentLabel: "Paris",
		countryCode: null,
		countryLabel: null,
		nafCode: "62.02A",
		nafLabel: "Conseil en systèmes et logiciels informatiques",
		workforceEma: 2256,
		totalWomen: 752,
		totalMen: 1504,
		hourlyWomen: 700,
		hourlyMen: 1400,
		globalAnnualMeanGap: 0.005,
		globalAnnualMedianGap: 0.0271,
		globalHourlyMeanGap: 0.0717,
		globalHourlyMedianGap: 0.0772,
		variableAnnualMeanGap: 0.1,
		variableAnnualMedianGap: 0.12,
		variableHourlyMeanGap: 0.207,
		variableHourlyMedianGap: 0.3127,
		variableProportionWomen: 0.571,
		variableProportionMen: 0.667,
		annualQuartile1ProportionWomen: 66.7,
		annualQuartile2ProportionWomen: 57.1,
		annualQuartile3ProportionWomen: 43.6,
		annualQuartile4ProportionWomen: 36.6,
		annualQuartile1ProportionMen: 33.3,
		annualQuartile2ProportionMen: 42.9,
		annualQuartile3ProportionMen: 56.4,
		annualQuartile4ProportionMen: 63.4,
		hourlyQuartile1ProportionWomen: 46.5,
		hourlyQuartile2ProportionWomen: 47.1,
		hourlyQuartile3ProportionWomen: 45.5,
		hourlyQuartile4ProportionWomen: 30.8,
		hourlyQuartile1ProportionMen: 53.5,
		hourlyQuartile2ProportionMen: 52.9,
		hourlyQuartile3ProportionMen: 54.5,
		hourlyQuartile4ProportionMen: 69.2,
		...overrides,
	};
}
