---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  labels:
    app: ${STARTUP}
    component: api
    namespace: ${STARTUP}-${ENVIRONMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        app: ${STARTUP}
        component: api
        namespace: ${STARTUP}-${ENVIRONMENT_NAME}
    spec:
      containers:
        - image: ${CI_REGISTRY_IMAGE}/api:${IMAGE_TAG}
          name: api
          ports:
            - containerPort: ${PORT}
          resources:
            requests:
              cpu: ${API_RESOURCE_CPU_REQUEST}
              memory: ${API_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${API_RESOURCE_CPU_LIMIT}
              memory: ${API_RESOURCE_MEMORY_LIMIT}
          livenessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: API_PORT
              value: "${PORT}"
            - name: KINTO_SERVER
              value: "kinto"
            - name: KINTO_BUCKET
              value: "${STARTUP}"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: KINTO_ADMIN_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: KINTO_ADMIN_PASSWORD
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_PORT
              value: "465"
            - name: MAIL_FROM
              value: "Index EgaPro <contact@${STARTUP}.beta.gouv.fr>"
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: MAIL_PASSWORD
            - name: API_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: ${STARTUP}
                  key: API_SENTRY_DSN
            - name: API_SENTRY_ENVIRONMENT
              value: "development"
