---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  labels:
    app: egapro
    component: api
    branch: egapro${SUFFIX_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - image: ${EGAPRO_REGISTRY}/api:${IMAGE_TAG}
          name: api
          ports:
            - containerPort: ${PORT}
          resources:
            requests:
              cpu: ${API_RESOURCE_CPU_REQUEST}
              memory: ${API_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${API_RESOURCE_CPU_LIMIT}
              memory: ${API_RESOURCE_MEMORY_LIMIT}
          livenessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: API_PORT
              value: "${PORT}"
            - name: KINTO_SERVER
              value: "kinto"
            - name: KINTO_BUCKET
              value: "egapro"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: KINTO_ADMIN_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: KINTO_ADMIN_PASSWORD
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_PORT
              value: "465"
            - name: MAIL_FROM
              value: "Index EgaPro <contact@egapro.beta.gouv.fr>"
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: MAIL_PASSWORD
            - name: API_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: egapro
                  key: API_SENTRY_DSN
            - name: API_SENTRY_ENVIRONMENT
              value: "development"
