---
kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app: egapro
    component: api
    branch: egapro${SUFFIX_BRANCH_NAME}
spec:
  selector:
    component: api
  ports:
    - port: ${PORT}
      name: api
