---
kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app: ${STARTUP}
    component: api
    namespace: ${STARTUP}-${ENVIRONMENT_NAME}
spec:
  selector:
    component: api
  ports:
    - port: ${PORT}
      name: api
