POST http://127.0.0.1:2626/token
Content-Type: application/json

{
    "email": "admin@gmail.com"
}

###

GET http://127.0.0.1:2626/declaration/841073315/2021
Cookie: api-key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2NTcyMzczNjd9.Ti7mDL2D5l8K4Qwqx6O2tkVz-KaUlmfbPY0sZpwP3Ic

###
GET http://127.0.0.1:2626/simulation/{{ token-simulation}}
