POST http://127.0.0.1:2626/token
Content-Type: application/json

{
    "email": "admin@gmail.com"
}

###

GET http://127.0.0.1:2626/declaration/834902959/2021
Cookie: api-key={{ token-api }}

###
GET http://127.0.0.1:2626/simulation/{{ token-simulation}}
