@token=renseigner_token
@SIREN=382616415

### Demande d'un token. La réponse est dans la console.
POST http://127.0.0.1:2626/token
Content-Type: application/json

{
    "email": "admin@gmail.com"
}

### Récupération des ownerships d'un SIREN

GET http://127.0.0.1:2626/ownership/{{SIREN}}
Cookie: api-key={{token}}