export type IconStyles =
  | "fr-fi-information-line"
  | "fr-icon-add-line"
  | "fr-icon-arrow-down-s-line"
  | "fr-icon-arrow-left-line"
  | "fr-icon-arrow-right-line"
  | "fr-icon-arrow-up-fill"
  | "fr-icon-arrow-up-s-line"
  | "fr-icon-calendar-line"
  | "fr-icon-edit-fill"
  | "fr-icon-error-fill"
  | "fr-icon-information-fill"
  | "fr-icon-line-fill"
  | "fr-icon-success-fill"
  | "fr-icon-success-line"
  | "fr-icon-user-fill"
  | "fr-icon-warning-fill"
  | "fr-icon-warning-line";
