name: Netlify deployment

on:
  push:
    branches:
      - '**'

  # workflow_dispatch:
  #   inputs:
  #     simuBranch:
  #       description: "Branche pour la simulation-déclaration"
  #       required: true
  #       default: "master"
  #     declaBranch:
  #       description: "Branche pour la déclaration directe"
  #       required: true
  #       default: "master"
  #     apiUrl:
  #       description: "URL de l'API"
  #       required: true
  #       default: "https://dev.egapro.fabrique.social.gouv.fr/api"

concurrency:
  cancel-in-progress: true
  group: netlify-deploy-${{ github.ref }}

jobs:

  build-simulation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile --force --non-interactive

    - name: Build app
      run: CI=false REACT_APP_EGAPRO_API_URL=https://dev.egapro.fabrique.social.gouv.fr/api yarn build

    - name: Upload react build
      uses: actions/upload-artifact@v2
      with:
        name: react-build
        path: build

  build-declaration:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: master
        repository: "SocialGouv/egapro-declaration"

    - name: Update API URL in Jekyll config
      run: |
        echo "EGAPRO_API_URL: ${EGAPRO_API_URL}" >> _config.yml

    - name: Install Jekyll
      run: |
        gem install -n /usr/local/bin jekyll bundler --user-install

    - name: Build Jekyll app
      run: |
        jekyll build --baseurl "/declaration"

    - name: Upload _site artifact
      uses: actions/upload-artifact@v2
      with:
        name: jekyll-site
        path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: [build-simulation, build-declaration]
    steps:

    - name: 
      uses: actions/download-artifact@v2
      with:
        name: react-build
        path: dist

    - uses: actions/download-artifact@v2
      with:
        name: jekyll-site
        path: dist/declaration

    - name: debug
      run: |
        ls -lah
        ls -lah dist/
        ls -lah dist/declaration/

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: ./dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
