on:
  push:
    branches: ["**"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

env:
  NODE_ENV: test

name: Tests
jobs:
  check-all:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.7'

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --force --non-interactive
          yarn setup-python

      - name: Up for tests API
        run: docker-compose up --build -d api db test_db

      - name: Check types
        run: yarn check-all

      - name: Down for tests API
        run: docker-compose down

      # TODO reenable. Next13 is not ready yet for proper testing
      # + using a mix between pageDir and appDir make tests harder to dev
      # - name: Run tests coverage for app
      #   run: yarn workspace app run test:coverage

      # - name: SonarCloud scan for app
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




